- README-ch.md
- README.md
Summary:
This PR adds an English readme to address English reading audience.
Note:
I am not quite sure what `yaml文件apply时，支持热变更` so my translation is only at best effort.
> add README for English readers

- Dockerfile
> fix: docker image is too large

- build.sh
- conf.json
- conf/conf.json
- conf/init.go
- samples/deploy/configmap/cloud.yaml
The ingress controller no dependencies with `etcd`, Related configuration and code deleted.
> fix: remove etcd configuration

- .asf.yaml
> doc: add asf.yaml .

- README.md
> doc: project status

- cmd/cmd.go
- cmd/ingress/ingress.go
- conf/config-default.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/log/default_logger.go
- pkg/log/default_logger_test.go
- pkg/log/logger.go
- pkg/log/logger_test.go
- pkg/log/options.go
- pkg/types/timeduration.go
- pkg/types/timeduration_test.go
Re designed a config module, supporting initializing from command line optoins and files.
Now this module is not in use. Will be used in the near future.
> chore: config module.

- .github/workflows/unit-test-ci.yml
- .gitignore
- Makefile
Closing https://github.com/apache/apisix-ingress-controller/issues/86.
> ci: go unit test coverage report

- .github/workflows/lint-checker.yml
- Makefile
- conf/errno.go
- conf/init.go
- log/log.go
- main.go
- pkg/ingress/apisix/annotation.go
- pkg/ingress/apisix/plugin.go
- pkg/ingress/apisix/route.go
- pkg/ingress/apisix/service.go
- pkg/ingress/apisix/upstream.go
- pkg/ingress/controller/controller.go
- pkg/ingress/controller/endpoint.go
- pkg/ingress/controller/store/store.go
- pkg/ingress/controller/watch.go
- pkg/route.go
> chore: gofmt

- cmd/ingress/ingress.go
- cmd/ingress/ingress_test.go
- conf/config-default.yaml
- pkg/log/logger.go
Closing https://github.com/apache/apisix-ingress-controller/issues/70.
> test: add test case for ingress command

- .github/workflows/lint-checker.yml
- .markdownlint.yml
Add a `.markdownlint.yml` config file
> feat(CI): add a GitHub Action to lint the Markdown

- docs/FAQ.md
Solve https://github.com/apache/apisix-ingress-controller/issues/33.
> doc: how to remove apisix admin key

- pkg/ingress/controller/apisix_route.go
- pkg/ingress/controller/apisix_service.go
- pkg/ingress/controller/apisix_tls.go
- pkg/ingress/controller/apisix_upstream.go
> fix: add item to workqueue with delay when syncFailed

- docs/FAQ.md
- go.mod
- go.sum
- pkg/ingress/apisix/tls.go
- pkg/ingress/apisix/tls_test.go
- pkg/ingress/controller/apisix_route.go
- pkg/ingress/controller/apisix_tls.go
- pkg/ingress/endpoint/ep.go
> fix: tls remove failed

- NOTICE
> docs: add NOTICE file.

- docs/install.md
> docs: the install.md doc lacks the creation of namespaces "ingress-apisix"

- README.md
- samples/deploy/deployment/ingress-controller.yaml
> docs: update images & readme

- Dockerfile
> chore: change the base image from alpine to centos

- docs/install.md
___
- Description
- How to fix?
___
___
> docs: use make cmd instead of docker build cmd

- docs/deployments/k3s.md
- docs/install.md
- docs/samples/proxy-the-httpbin-service.md
___
- Description
- How to fix?
___
___
> doc: add document about running ingress apisix on k3s

- docs/deployments/aws.md
rename AWS EKS to Amazon EKS
___
- Description
- How to fix?
___
___
> chore(doc): rename AWS EKS to Amazon EKS

- docs/deployments/k3s-rke.md
- docs/install.md
___
- Description
- How to fix?
___
___
> doc: also run on Rancher RKE

- pkg/id/idgen.go
- pkg/id/idgen_test.go
___
- Description
- How to fix?
___
___
> feat: add pkg idgen

- docs/deployments/tke.md
- docs/install.md
___
- Description
- How to fix?
___
___
> doc: add doc about how to run on tke

- docs/deployments/kubesphere.md
___
- Description
- How to fix?
___
___
> doc: run ingress apisix on kubesphere

- docs/deployments/kubesphere.md
- docs/install.md
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
> refine the deployment guide of kubesphere, reorder the list in instll.md

- Makefile
Fix: https://github.com/apache/apisix-ingress-controller/issues/186
> chore:add ginkgo check before e2e-test(apache #186)

- README.md
Signed-off-by: fukiki <one.fhh@163.com>
Fix #193 
> doc: Add Apache APISIX link in README

- README.md
> doc:add milestone link

- cmd/ingress/ingress_test.go
- pkg/ingress/controller/controller.go
- pkg/seven/state/service_worker.go
> fix: fix error check lint errors

- cmd/ingress/ingress_test.go
- pkg/api/router/router.go
- pkg/apisix/cluster.go
- pkg/ingress/apisix/tls_test.go
> fix: fix lint errors

- .github/workflows/e2e-test-ci.yml
- Makefile
- test/e2e/e2e.go
- utils/minikube.sh
___
- Description
- How to fix?
___
___
> ci: install and start minikube manully

- go.sum
- pkg/apisix/resource.go
- pkg/apisix/upstream.go
- pkg/ingress/apisix/upstream.go
- pkg/ingress/controller/endpoint.go
- pkg/kube/apisix/apis/config/v1/types.go
- pkg/types/apisix/v1/types.go
- test/e2e/e2e.go
- test/e2e/features/scheme.go
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/ingress/namespace.go
- test/e2e/ingress/sanity.go
- test/e2e/scaffold/scaffold.go
___
- Description
- How to fix?
___
___
> chore: support grpc scheme in ApisixUpstream

- charts/apisix-ingress-controller/templates/rbac.yaml
- samples/deploy/rbac/apisix_view_clusterrole.yaml
- test/e2e/scaffold/ingress.go
- test/e2e/scaffold/scaffold.go
…w_clusterrole.yaml
___
- Description
- How to fix?
___
___
> fix: add write permission for leases

- charts/apisix-ingress-controller/templates/rbac.yaml
- samples/deploy/rbac/apisix_view_clusterrole.yaml
- test/e2e/scaffold/ingress.go
ApisixSSL resources operation will fail.
___
- Description
- How to fix?
___
___
> fix: secrets permissions missing

- charts/apisix-ingress-controller/templates/deployment.yaml
> feat: reload deployment when config changed

- test/e2e/testdata/apisix-gw-config-default.yaml
- test/e2e/testdata/apisix-gw-config.yaml
___
- Description
There is a bug in Apache APISIX 2.3 or higher version, the rendered nginx.conf is malformed (the resolver directive).
- How to fix?
Just commented the `dns_resolver_valid` option in config-default.yaml and config.yaml.
___
___
> fix: CI broken problem

- README.md
___
Fix the **README.md** SDK doc link broken.
> docs: fix SDK doc link broken

- README.md
- install.md
- Related issues #257 
___
Move the **install.md** file to the top-level directory, and modify the **install.md** relative path.
> docs: move install.md location to top level directory

- .markdownlint.yml
- docs/en/latest/CRD-specification.md
- docs/en/latest/FAQ.md
- docs/en/latest/config.json
- docs/en/latest/contribute.md
- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/k3s-rke.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/minikube.md
- docs/en/latest/deployments/tke.md
- docs/en/latest/design.md
- docs/en/latest/development.md
- docs/en/latest/samples/index.md
- docs/en/latest/samples/proxy-the-httpbin-service-with-ingress.md
- docs/en/latest/samples/proxy-the-httpbin-service.md
- docs/en/latest/usage.md
> docs: added meta info

- docs/en/latest/config.json
> docs: remove extra docs category

- docs/en/latest/CRD-specification.md
- pkg/kube/translation/ingress.go
___
- Description
- How to fix?
___
___
> chore: fix whitespace

- CHANGELOG.md
- cmd/ingress/ingress.go
- conf/config-default.yaml
- docs/en/latest/CRD-specification.md
- docs/en/latest/FAQ.md
- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/k3s-rke.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/minikube.md
- docs/en/latest/deployments/tke.md
- docs/en/latest/development.md
- pkg/apisix/upstream.go
- pkg/config/config_test.go
- pkg/ingress/controller/apisix_upstream.go
- pkg/ingress/controller/controller.go
- pkg/ingress/controller/ingress.go
- pkg/kube/apisix/apis/config/v1/types.go
- pkg/seven/apisix/plugins.go
- pkg/seven/state/builder.go
- pkg/types/apisix/v1/types.go
- pkg/version/version.go
- samples/deploy/configmap/apisix-ingress-cm.yaml
- test/e2e/README.md
- test/e2e/ingress/resourcepushing.go
- test/e2e/scaffold/k8s.go
- test/e2e/testdata/apisix-gw-config.yaml
___
- Description
- How to fix?
___
___
> chore: fix spelling

- docs/en/latest/getting-started.md
___
- Description
- How to fix?
___
___
> doc: add design link in getting started

- docs/en/latest/getting-started.md
Fix https://github.com/apache/apisix-website/issues/256
___
- Description
Fix the website broken links.
- How to fix?
> docs: fix website broken links

- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/k3s-rke.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/minikube.md
- docs/en/latest/deployments/tke.md
- Related issues #277 
___
- Description
- Fix #277
Update deployment docs repository url.
- How to fix?
> docs: update deployments repository url

- pkg/kube/apisix/apis/config/v1/types.go
- pkg/kube/apisix/apis/config/v2alpha1/types.go
> chore: add yaml tags for types

- docs/en/latest/config.json
add CHANGELOG.md in  sidebar
___
> feat: add CHANGELOG.md in  sidebar

- pkg/ingress/controller/apisix_route.go
- pkg/ingress/controller/apisix_upstream.go
- pkg/ingress/controller/endpoint.go
- pkg/ingress/controller/ingress.go
> fix: workqueue need to retry when failed

- test/e2e/plugins/request_id.go
___
- Description
- How to fix?
___
___
> test: add e2e test cases for request-id

- pkg/apisix/resource.go
- pkg/apisix/route.go
- pkg/kube/translation/apisix_route.go
- test/e2e/ingress/resourcepushing.go
___
- Description
- How to fix?
___
___
> fix: priority in route rules is not passed to APISIX

- pkg/kube/translation/apisix_route.go
- pkg/kube/translation/apisix_route_test.go
___
- Description
- How to fix?
___
___
> fix: route rule name cannot be empty and duplicated

- test/e2e/plugins/echo.go
___
- Description
- How to fix?
___
___
> test: add test cases for echo plugin

- Dockerfile
- Makefile
___
- Description
- How to fix?
___
This PR optimized the image building speed by specifying the `go mod download` before copying all files so the docker build-cache about go modules can be leveraged as soon as possible (as long as the `go.mod`  and `go.sum` files don't change).
___
> chore: optimize dockerfile

- test/e2e/plugins/response_rewrite.go
___
- Description
- How to fix?
___
___
> test: add e2e test cases for response-rewrite plugin

- docs/en/latest/deployments/ack.md
___
- Description
- How to fix?
___
___
> ack env install apisix

- docs/en/latest/FAQ.md
___
- Description
- How to fix?
___
___
> doc: helm chart CRDs

- test/e2e/features/traffic_split.go
- test/e2e/scaffold/scaffold.go
___
- Description
- How to fix?
___
___
> test: add DP test cases in traffic split e2e

- docs/en/latest/getting-started.md
___
- Description
- How to fix?
___
___
> doc: describe the compatibility with APISIX

- conf/config-default.yaml
- test/e2e/plugins/request-validation.go
___
- Description
- How to fix?
___
___
> test: add e2e test cases for request-validation plugin

- pkg/kube/translation/apisix_route.go
- pkg/kube/translation/apisix_ssl.go
- pkg/kube/translation/ingress.go
- pkg/types/apisix/v1/types.go
- test/e2e/ingress/resourcepushing.go
- test/e2e/ingress/ssl.go
https://github.com/apache/apisix-ingress-controller/issues/242
___
- Description
- How to fix?
___
___
> feat:add labels for resources

- pkg/kube/translation/translator.go
fix #381
translator support for extensions/v1beta1.Ingress
> fix: correctly translate ingress in extensions/v1beta1 group version

- test/e2e/plugins/referer-restriction.go
close #362
___
- Description
- How to fix?
___
___
> add e2e test cases for referer-restriction plugin

- samples/deploy/crd/v1beta1/ApisixRoute.yaml
- samples/deploy/crd/v1beta1/ApisixTls.yaml
___
- Description
- How to fix?
___
___
> feat: apisixtls schema

- test/e2e/plugins/api_breaker.go
- test/e2e/testdata/apisix-gw-config.yaml
___
- Description
- How to fix?
___
___
> test: add api-breaker plugin e2e test cases

- docs/en/latest/config.json
fix: [#324](https://github.com/apache/apisix-website/issues/324)
> docs: remove getting started inside getting started category

- docs/en/latest/config.json
fix: [#323](https://github.com/apache/apisix-website/issues/323)
> docs: design of  ingress-controller  is  included in the sidebar

- pkg/ingress/apisix_route.go
- pkg/ingress/apisix_tls.go
- pkg/ingress/apisix_upstream.go
- pkg/ingress/status.go
- pkg/kube/apisix/apis/config/v1/types.go
- pkg/kube/apisix/apis/config/v1/zz_generated.deepcopy.go
- pkg/kube/apisix/client/clientset/versioned/typed/config/v1/apisixtls.go
- pkg/kube/apisix/client/clientset/versioned/typed/config/v1/apisixupstream.go
- pkg/kube/apisix/client/clientset/versioned/typed/config/v1/fake/fake_apisixtls.go
- pkg/kube/apisix/client/clientset/versioned/typed/config/v1/fake/fake_apisixupstream.go
https://github.com/apache/apisix-ingress-controller/issues/395
___
- Description
- How to fix?
___
___
> feat: add upstream status & tls status

- docs/en/latest/concepts/apisix_route.md
___
- Description
Fix spelling errors in apisix_route.md
- How to fix?
> docs: fix spelling errors in apisix_route.md

- docs/en/latest/FAQ.md
- docs/en/latest/concepts/apisix_upstream.md
- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/k3s-rke.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/minikube.md
- docs/en/latest/deployments/tke.md
- docs/en/latest/design.md
- docs/en/latest/development.md
- docs/en/latest/getting-started.md
- docs/en/latest/practices/proxy-the-httpbin-service-with-ingress.md
- docs/en/latest/practices/proxy-the-httpbin-service.md
- docs/en/latest/references/apisix_upstream.md
fix: [#325](https://github.com/apache/apisix-website/issues/325)
___
> docs: broken links in markdown files

- samples/deploy/crd/v1beta1/ApisixUpstream.yaml
- test/e2e/features/healthcheck.go
This Pull Request adds schema for `ApisixUpstream`.
___
- Description
- How to fix?
___
___
> chore: add schema for ApisixUpstream

- cmd/ingress/ingress.go
- conf/config-default.yaml
- pkg/apisix/apisix.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/ingress/apisix_upstream.go
- pkg/ingress/controller.go
- pkg/ingress/manifest.go
The processing for the apisix cluster was optimized, so it can be easier to implement the multiple clusters support in the future.
> chore: optimize the apisix cluster processing

- pkg/kube/ingress.go
> fix wrong group version for extensions/v1beta1.Ingress

- pkg/ingress/manifest.go
- test/e2e/ingress/resourcepushing.go
___
- Description
See https://github.com/apache/apisix-ingress-controller/issues/421 for details.
- How to fix?
Check the return error, if it's `ErrStillInUse`, logging this error and continue.
___
___
> fix: handle upstream caching delete correctly

- pkg/kube/translation/apisix_route.go
- pkg/kube/translation/apisix_route_test.go
> fix: cookie in exprs should remains unchanged

- pkg/ingress/ingress.go
___
- Description
- How to fix?
___
___
> chore: add error logging in ingress

- CHANGELOG.md
- Makefile
- docs/en/latest/getting-started.md
> release 0.6.0

- pkg/apisix/cluster.go
- pkg/ingress/controller.go
#448 
___
- Description
- How to fix?
___
___
> fix: wait for the default cluster ready continuously

- samples/deploy/rbac/apisix_view_clusterrole.yaml
- test/e2e/scaffold/ingress.go
https://github.com/apache/apisix-ingress-controller/issues/434
> fix: add status subresource permission in clusterRole

- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/k3s-rke.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/minikube.md
- docs/en/latest/deployments/tke.md
This change was introduced from
https://github.com/apache/apisix-helm-chart/pull/74
___
- Description
- How to fix?
___
___
> docs: fix APISIX helm installation

- .asf.yaml
___
- Description
- How to fix?
___
___
> chore: change the required PR approving number to 2

- docs/en/latest/references/apisix_route_v1.md
___
- Description
Fix broken links.
> docs: fix broken links

- pkg/apisix/cluster.go
> fix: remove upstream which is ref by multi-routes cause retry

- pkg/ingress/controller.go
> fix: event record scheme error

- test/e2e/ingress/ingress.go
- test/e2e/scaffold/k8s.go
Fixes #255
___
Add basic e2e test for headless service.
> test: add basic headless service e2e test

- test/e2e/ingress/tcp.go
> chore: e2e case for tcp proxy is unstable

- test/e2e/plugins/ip-restriction.go
> chore: fix e2e ip-restriction plugin text

- Makefile
> fix: fatal error reported when run make build in release src

- docs/en/latest/config.json
- docs/en/latest/practices/index.md
- docs/en/latest/practices/step-by-step.md
- docs/en/latest/practices/the-hard-way.md
___
Add installation guide from native k8s yaml step by step doc..
> docs: ingress apisix the hard way

- pkg/ingress/ingress.go
- pkg/ingress/ingress_test.go
#475 
___
- Description
ingress_class configuration is invalid
- How to fix?
we should use controller.config.Kubernetes.IngressClass  instead config.ingressClass
> fix: ingress_class configuration invalid(#475)

- samples/deploy/deployment/ingress-controller.yaml
> chore: add dnsPolicy for sample deployment

- docs/en/latest/deployments/ack.md
- https://github.com/apache/apisix-website/issues/326
___
- Description
- How to fix?
___
___
- Source branch: fixlinks
- Target branch: master
> fix: ack.md link fix

- .github/workflows/e2e-test-ci.yml
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
___
- Description
Complement to #505.
Sorry forgot recursively checkout to get the submodule 😿
> ci: fix cancel workflow not working

- .dockerignore
> chore: add docker ignore to avoid unwanted cache miss

- samples/deploy/crd/v1beta1/ApisixTls.yaml
- samples/deploy/crd/v1beta1/ApisixUpstream.yaml
- samples/deploy/rbac/apisix_view_clusterrole.yaml
Fixes #511, fixes #512
___
- Description
Add `events` permission and subresource
- How to fix?
> feat: add permission to events, fix missing subresources in crd

- .github/workflows/license-checker.yml
___
- Description
- How to fix?
Not pin the version to avoid missing bugfix.
___
___
> Change skywalking-eyes version to main

- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/lint-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .gitmodules
By adding path filtering, unnecessary CI time-consuming can be reduced.
> ci: add changes filter

- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/lint-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
___
- Description
fix CI path filter logics.
> fix: CI path filter

- docs/en/latest/development.md
___
- Description
- How to fix?
___
___
> docs: update development.md

- pkg/ingress/controller.go
- pkg/types/apisix/v1/types.go
- samples/deploy/crd/v1beta1/kustomization.yaml
- test/e2e/features/consumer.go
- test/e2e/scaffold/k8s.go
___
This was introduced through #516  while resolving the conflict. :crying_cat_face:
> fix: nil pointer dereference

- test/e2e/plugins/echo.go
it has been removed.
xref: https://github.com/apache/apisix/pull/4055
> chore: remove echo plugin's auth test case.

- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
resolve #493 
This PR adds draft PRs to skip CI.
> ci: do not run workflows for draft PRs

- docs/en/latest/practices/check-crd-status.md
ref to : https://github.com/apache/apisix-ingress-controller/issues/537
> docs: how to check resource status

- Makefile
- pkg/apisix/resource.go
- pkg/ingress/apisix_route.go
- pkg/kube/translation/apisix_route.go
- pkg/kube/translation/apisix_route_test.go
- pkg/kube/translation/translator.go
- pkg/kube/translation/util.go
- test/e2e/ingress/resourcepushing.go
- test/e2e/scaffold/k8s.go
> fix: use not strictly translation when remote ApisixRoute

- docs/en/latest/deployments/k3s-rke.md
> fixed a typo of k3s-rke.md

- docs/en/latest/practices/the-hard-way.md
- test/e2e/scaffold/ingress.go
follow #230
___
- Description
- How to fix?
___
___
> chore: cleanup apisixservice.

- docs/en/latest/concepts/apisix_route.md
- docs/en/latest/design.md
- docs/en/latest/practices/check-crd-status.md
- docs/en/latest/practices/mtls.md
- docs/en/latest/practices/proxy-the-httpbin-service.md
- docs/en/latest/practices/the-hard-way.md
fix: https://github.com/apache/apisix-ingress-controller/issues/584
> chore: add udp usage & upgrade the verion of ApisixRoute

- samples/deploy/deployment/ingress-controller.yaml
https://github.com/apache/apisix-ingress-controller/issues/581
___
- Description
- How to fix?
modify ingress controller docker image version to 1.0.0
___
___
> fix: modify ingress controller docker image version to 1.0.0

- docs/en/latest/FAQ.md
https://github.com/apache/apisix-website/issues/424
___
- Description
When I was dealing with the above issue, I found that the FAQ.md file format in this project was inconsistent with other APISIX projects, which made it inconvenient to deal with.
- How to fix?
Refer to the apisix-dashboard project to modify the format of FAQ.md.
___
___
> docs: modify the format of FAQ.md

- pkg/ingress/status.go
- pkg/kube/apisix_route.go
> fix: add v2beta1 logic

- pkg/apisix/resource_test.go
- pkg/config/config_test.go
- pkg/kube/translation/apisix_route_test.go
- pkg/kube/translation/ingress_test.go
- pkg/kube/translation/plugin_test.go
- test/e2e/ingress/resourcepushing.go
- test/e2e/scaffold/httpbin.go
___
- Description
- How to fix?
___
**add assertion for test cases**
1. `assert.NotNil(t, err)`
2. 
___
> test: add assert for test cases

- CHANGELOG.md
- README.md
- docs/en/latest/getting-started.md
> docs: add declarations for the version of APISIX

- pkg/ingress/controller.go
___
- Description
- How to fix?
___
___
> fix: timer leak memory

- pkg/kube/apisix_route.go
- test/e2e/go.sum
- test/e2e/ingress/resourcepushing.go
- test/e2e/scaffold/k8s.go
- test/e2e/scaffold/scaffold.go
- test/e2e/testdata/apisix-gw-config.yaml
> fix: sync apisix failed when use v2beta1 ApisixRoute

- samples/deploy/crd/v1beta1/ApisixRoute.yaml
> fix: ApisixRoute printcolumns

- docs/en/latest/references/apisix_tls.md
> docs: update mTLS support in ApisixTls reference

- .github/workflows/codeql-analysis.yml
___
- Skip CodeQL if go files have no changes
> chore: skip CodeQL if go files have no changes

- .github/workflows/lint-checker.yml
- .gitmodules
- README.md
- link-check-config.json
___
- Add link check for markdown files
> feat: add link check

- test/e2e/ingress/resourcepushing.go
> fix: remove the step of deleting httpbinsvc

- Makefile
- docs/en/latest/practices/the-hard-way.md
- samples/deploy/crd/kustomization.yaml
- samples/deploy/kustomization.yaml
___
- Description
* upgrade admission apiversion to v1
* create a `kustomization.yaml` file under `samples/deploy/crd/`, so we don’t need to specify its version
- How to fix?
___
___
> feat: upgrade admission apiversion to v1

- samples/deploy/crd/v1/ApisixRoute.yaml
- samples/deploy/crd/v1/ApisixUpstream.yaml
___
- Description
fix: CRD v1 preserve unknown fields
- How to fix?
___
___
> fix: CRD v1 preserve unknown fields

- test/e2e/plugins/response_rewrite.go
see https://github.com/apache/apisix/issues/5370
> fix: wrong var type in response_rewrite e2e

- docs/en/latest/practices/proxy-the-httpbin-service.md
[https://github.com/apache/apisix-ingress-controller/issues/762](https://github.com/apache/apisix-ingress-controller/issues/762)
___
- How to fix?
Add missing space
> Fix bug typo in yaml

- pkg/kube/translation/apisix_route.go
> fix: ApisixRoute backendPoint duplicate (#732)

- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/tke.md
___
- Add description for ingress version
- Add description for ssl
- Add description for default key config
> Docs: add more config example

- pkg/api/router/apisix_healthz.go
- pkg/api/router/router_test.go
- pkg/api/router/types.go
- pkg/api/server.go
- pkg/ingress/controller.go
Fix #567
___
- Implement apisix healthz check, sharing health check state with controller, add unit tests.
Comment if something is wrong, then I'll change it.
> feat: implement apisix healthz check

- README.md
The [image](https://github.com/apache/apisix-ingress-controller#internal-architecture) is to flat, so I change the changed the ratio of height and width.
solved #796
> docs(READEME.md): change image size

- samples/deploy/crd/v1/ApisixRoute.yaml
> bug: fix typo in ApidixRoute CRD

- pkg/ingress/ingress.go
Signed-off-by: champly <champly@outlook.com>
#855
> fix ingress delete panic

- docs/en/latest/development.md
> docs: add pre-commit todo in the development guide

- docs/en/latest/concepts/apisix_route.md
- docs/en/latest/practices/check-crd-status.md
- docs/en/latest/practices/manage-certificates-with-cert-manager.md
- docs/en/latest/practices/mtls.md
- docs/en/latest/practices/mtls/route.yaml
- docs/en/latest/references/apisix_route_v2beta3.md
Resolved [#915](https://github.com/apache/apisix-ingress-controller/issues/915)
> chore: upgrade apiVersion from v2beta1 to v2beta3

- docs/en/latest/config.json
Remove the useless development block from the sidebar configuration to prevent the apisix-website from failing to build
> docs: remove development from sidebar config

- test/e2e/suite-plugins/server-info.go
fix the e2e test case of the server-info plugin for APISIX v2.13 
#952
> feat: fix the e2e test case of the server-info plugin for APISIX v2.13 

- docs/en/latest/references/apisix_route_v2beta3.md
- test/e2e/README.md
> docs: fix subset field typo

- docs/en/latest/references/apisix_upstream.md
> docs: update apisix_upstream.md

- CHANGELOG.md
- releases/v1.4.1.toml
> chore: Add v1.4.1 changelog

- Makefile
> chore: bump version to v1.4.1

- Makefile
> chore: update apisix to 2.13.1

- docs/en/latest/practices/manage-certificates-with-cert-manager.md
- docs/en/latest/practices/manage-ingress-certificates-with-cert-manager.md
> docs: fix link in certificate management docs (#998)

- CHANGELOG.md
- Makefile
- releases/v1.4.1.toml
Cherry-pick from v1.4.0 branch
* v1.4.1 changelog 
* bump version to v1.4.1
> chore: Changelog for 1.4.1

- docs/en/latest/contribute.md
What did you do:  
* Fixed push-images error.
* More detailed local development process.
> doc: update contribute.md doc

- samples/deploy/crd/v1/ApisixClusterConfig.yaml
- test/e2e/scaffold/cluster_config.go
- test/e2e/scaffold/scaffold.go
- test/e2e/suite-features/global_rule.go
> e2e-test: add e2e tests and CRDs for ApisixClusterConfig v2

- docs/en/latest/practices/how-to-use-go-plugin-runner-in-apisix-ingress.md
about how to use go plugin runner in APISIX Ingress.
Methion issue #921 
This will improve the readability of the document. Improve the usability of APISIX Ingress.
> docs: add "how to use go plugin runner with APISIX Ingress"

- samples/deploy/crd/v1/ApisixPluginConfig.yaml
- test/e2e/scaffold/scaffold.go
- test/e2e/suite-plugins/plugin_config.go
> e2e-test: add e2e tests for ApisixPluginConfig v2

- samples/deploy/crd/v1/ApisixRoute.yaml
fix: https://github.com/apache/apisix-ingress-controller/issues/1092
> fix: make ApisixRouteHTTPBackend support serivce name

- .github/dependabot.yml
This is a Go project with a lot of dependencies, but we update them very infrequently.
Open Github's dependabot, it can be updated automatically to improve the security of this project
> chore: enable dependabot for security

- docs/en/latest/tutorials/enable-authentication-and-restriction.md
> doc: fix enable-authentication-and-restriction.md link failed

- pkg/ingress/apisix_route.go
- pkg/ingress/utils/manifest.go
- pkg/log/default_logger.go
- pkg/log/logger.go
Add some logs for syncManifest to help debug errors.
> chore: add log for syncManifest delete upstream

- .github/workflows/license-checker.yml
> ci: pin skywalking-eyes to v0.3.0 release

- .asf.yaml
- .github/dependabot.yml
ref: https://lists.apache.org/thread/txxnbo649lv7hqy44r08zmxtl527s69d
I got an email about the notifications feature error.
But after reading the documentation, I didn't find the reason for the error, and this configuration has not been modified recently.
So I decided to delete notifications related configuration. This will use the default configuration
I have referenced other projects, the default configuration can already meet our needs
> chore: change description and labels for this project

- docs/en/latest/config.json
Fix the configuration of file id in sidebar in v1.2.0, so that apisix-website can build the documentation correctly.
Related to #1167, not yet fixed in apisix-website.
> doc: correct sidebar file id in v1.2.0

- docs/en/latest/concepts/annotations.md
- docs/en/latest/concepts/apisix_cluster_config.md
- docs/en/latest/concepts/apisix_route.md
- docs/en/latest/concepts/apisix_tls.md
- docs/en/latest/concepts/apisix_upstream.md
- docs/en/latest/design.md
- docs/en/latest/plugins/prometheus.md
- docs/en/latest/tutorials/check-crd-status.md
- docs/en/latest/tutorials/enable-authentication-and-restriction.md
- docs/en/latest/tutorials/how-to-access-Apache-APISIX-Prometheus-Metrics-on-k8s.md
- docs/en/latest/tutorials/how-to-use-go-plugin-runner-in-apisix-ingress.md
- docs/en/latest/tutorials/manage-certificates-with-cert-manager.md
- docs/en/latest/tutorials/mtls.md
- docs/en/latest/tutorials/mtls/mtls.yaml
- docs/en/latest/tutorials/mtls/route.yaml
- docs/en/latest/tutorials/mtls/tls.yaml
- docs/en/latest/tutorials/proxy-grpc-service.md
- docs/en/latest/tutorials/proxy-the-httpbin-service.md
- docs/en/latest/tutorials/the-hard-way.md
- docs/en/latest/upgrade.md
> docs: update all api-version to v2

- pkg/ingress/apisix_upstream.go
* panic: interface conversion: interface {} is string, not kube.ApisixUpstreamEvent
> fix: apisix_upstream sync panic

- pkg/ingress/apisix_route.go
- pkg/ingress/controller.go
- pkg/ingress/ingress.go
- pkg/kube/translation/apisix_route.go
- pkg/kube/translation/ingress.go
- pkg/kube/translation/translator.go
- test/e2e/suite-chore/consistency.go
> fix: translate error of old Ingress

- test/e2e/scaffold/scaffold.go
- test/e2e/suite-ingress/suite-ingress-features/resourcesync.go
* By reducing the interval, and verify witness the robustness of the synchronization function of all examples.
* Add ApisixUpstream and ApisixPluginConfig  test cases.
> e2e: add sync test case

- README.md
- docs/en/latest/FAQ.md
* Reorder sections
* Merge sections
* Remove license section as GitHub makes it prominently clear
> doc: Refactor the README

- docs/en/latest/config.json
- install.md
> docs: add installation on KIND to index

- README.md
Update the new link for contributors over time
> chore: update contributor over time link for README

- cmd/ingress/ingress_test.go
> fix: TestRotateLog

- pkg/apisix/resource_test.go
- pkg/types/apisix/v1/types.go
> [v1.5.0 cherry-pick] fix: nodes convert failed (#1222)

- .github/workflows/k8s-timer-ci.yml
https://github.com/apache/apisix-ingress-controller/actions/runs/2900687740
* Default branch missing in timer-ci
> ci: set default_branch

- docs/en/latest/references/apisix_route_v2.md
- docs/en/latest/references/apisix_route_v2beta3.md
> docs:add ApisixUpstream healthCheck explanation to resolveGranularity

- README.md
- powered-by.md
> docs: add powered-by.md

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
> [v1.5 cherry-pick]chore: protect v1.5.0 and enable CI for it (#1294)

- pkg/api/validation/utils.go
- pkg/api/validation/utils_test.go
- pkg/ingress/namespace/provider.go
- test/e2e/scaffold/ingress.go
- test/e2e/scaffold/k8s.go
- test/e2e/scaffold/scaffold.go
- test/e2e/suite-ingress/suite-ingress-features/namespace.go
> fix: namespace_selector invalid when restarting - v1.5.0

- pkg/ingress/apisix_cluster_config.go
- pkg/ingress/apisix_consumer.go
- pkg/ingress/apisix_upstream.go
- pkg/ingress/endpointslice.go
* #1267 
* Coredump caused by type assertion failure.
> [v1.5] fix: type assertion failed

- pkg/ingress/gateway/gateway_httproute.go
- test/e2e/scaffold/k8s.go
- test/e2e/suite-gateway/gateway_httproute.go
> feat: support update and delete of HTTPRoute (#1315)

- README.md
Add APISIX slack channel invitation badge
> docs: add slack invitation badge

- pkg/ingress/status.go
> [v1.5 cherry-pick]fix: crd resource status is not updated (#1335)

- powered-by.md
> docs: update user cases

- powered-by.md
> docs: modify powered-by.md

- CHANGELOG.md
- Makefile
- docs/en/latest/FAQ.md
* bump version
* add changelog
> chore: release v1.5.0

- CHANGELOG.md
- Makefile
> chore: release v1.5.0 (#1360)

- .github/workflows/e2e-test-ci.yml
- docs/en/latest/concepts/apisix_upstream.md
Updates the documentation of ApisixUpstream concept.
> docs: update ApisixUpstream docs

- pkg/ingress/status.go
> fix: handle v2 ApisixPluginConfig status

- docs/en/latest/concepts/apisix_cluster_config.md
- docs/en/latest/concepts/apisix_tls.md
Update "ApisixTls" and "ApisixClusterConfig" docs.
> docs: update "ApisixTls" and "ApisixClusterConfig"

- docs/en/latest/tutorials/mtls.md
Fix `server-secret.yaml` link in `mtls.md`. Fixing part of #1430. (`master` branch)
> docs: fix `server-secret.yaml` link in `mtls.md`

- docs/en/latest/tutorials/mtls.md
Fix `server-secret.yaml` link in `mtls.md`. Fixing part of #1430. (`v1.5.0` branch)
> docs: fix `server-secret.yaml` link in `mtls.md` (v1.5.0)

- cmd/ingress/ingress.go
- conf/config-default.yaml
- pkg/config/config.go
- pkg/config/config_test.go
ref: https://github.com/apache/apisix-ingress-controller/issues/908#issuecomment-1073859354
> feat: delete "app_namespace" param

- Dockerfile
modify Dockerfile go version from 1.18 to 1.19 , consist with go mod.
relate to #1290 #1357
> modify Dockerfile go version from 1.18 to 1.19 ,consist with go mod

- docs/en/latest/references/apisix_upstream.md
Updates the ApisixUpstream reference page.
> docs: update ApisixUpstream reference

- pkg/kube/translation/apisix_route.go
> bug: failed to reflect pluginConfig delete to cache(#1439)

- CHANGELOG.md
- Makefile
- docs/en/latest/references/apisix_upstream.md
- releases/v1.5.1.toml
Add CHANGELOG and bump version.
> chore: v1.5.1 release

- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- README.md
- powered-by.md
* Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: update actions and add more user cases.

- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- README.md
- powered-by.md
Reverts apache/apisix-ingress-controller#1478
```
[e2e-test-ci: .github#L1](https://github.com/apache/apisix-ingress-controller/pull/1480/files#annotation_6560699259)
Error when evaluating 'strategy' for job 'e2e-test'. .github/workflows/e2e-test-ci.yml (Line: 154, Col: 16): Error parsing fromJson,.github/workflows/e2e-test-ci.yml (Line: 154, Col: 16): Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/e2e-test-ci.yml (Line: 154, Col: 16): Unexpected type of value '', expected type: Sequence.
```
> Revert "chore: update actions and add more user cases."

- README.md
- powered-by.md
> docs: add more user cases

- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/k8s-timer-ci.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
* Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: bump actions.

- cmd/ingress/ingress.go
- cmd/ingress/ingress_test.go
> fix:sanitize log output when exposing sensitive values

- docs/en/latest/concepts/apisix_upstream.md
service do not have a field 'portLevelSettings', maybe a typo
```
$ kubectl explain service.spec.portLevelSettings      
error: field "portLevelSettings" does not exist
```
> docs: fix typo

- docs/en/latest/upgrade.md
> doc: update upgrade guide

- docs/en/latest/concepts/annotations.md
- pkg/providers/ingress/translation/annotations/plugins/plugins.go
- pkg/providers/ingress/translation/annotations/plugins/response_rewrite.go
- pkg/providers/ingress/translation/annotations/plugins/response_rewrite_test.go
- pkg/providers/ingress/translation/annotations/types.go
- test/e2e/suite-annotations/response_rewrite.go
Support 4 annotations of response-rewrite:
* k8s.apisix.apache.org/enable-response-rewrite
* k8s.apisix.apache.org/response-rewrite-status-code
* k8s.apisix.apache.org/response-rewrite-body
* k8s.apisix.apache.org/response-rewrite-body-base64
Close #575
> feat: support annotation of response-rewrite

- docs/en/latest/tutorials/external-service.md
> docs: add external service tutorial

- docs/en/latest/tutorials/proxy-the-httpbin-service-with-ingress.md
Updates the ingress controller tutorial and makes it more straighforward and provide relevant example usages.
> docs: update Ingress controller httpbin tutorial

- CHANGELOG.md
- Makefile
- releases/v1.5.1.toml
- releases/v1.6.0.toml
> chore: 1.6.0-rc1 release

- docs/en/latest/tutorials/check-crd-status.md
Updates the tutorial on checking the synchronization status of APISIX CRDs.
> docs: update synchronization status check docs

- docs/en/latest/tutorials/the-hard-way.md
Update tutorial on installing APISIX in Kubernetes.
> update tutorial on installing APISIX in Kubernetes

- pkg/providers/ingress/translation/annotations/upstreamscheme/upstreamscheme.go
> chore: useless annotations warn logs

- pkg/providers/ingress/translation/annotations/upstreamscheme/upstreamscheme.go
Co-authored-by: rongxin <alinsran@apache.org>
> [cherry-pick v1.6] chore: extra annotations logs (#1549)

- conf/config-default.yaml
- pkg/config/config.go
- pkg/config/config_test.go
Co-authored-by: Jintao Zhang <zhangjintao@apache.org>
> [cherry-pick v1.6] fix: bad configuration item: apisix-admin-api-version (#1551)

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
> chore: set v1.6 as protect branch

- docs/en/latest/tutorials/match-stream-route-by-sni.md
> docs: add match stream route with SNI tutorial

- pkg/config/config.go
> chore: admin-api default version v2

- pkg/config/config.go
Co-authored-by: rongxin <alinsran@apache.org>
We should keep the v2 Admin API available to users without any configuration. to avoid breaking changes
> [cherry-pick v1.6] chore: admin-api default version v2 (#1558)

- docs/en/latest/deployments/aws.md
Add instructions to use Network LoadBalancer in AWS.
> docs: add instructions to use Network LoadBalancer

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- CHANGELOG.md
> chore: add change log for v1.6.0

- pkg/providers/apisix/translation/apisix_route.go
- test/e2e/suite-chore/consistency.go
- test/e2e/suite-ingress/suite-ingress-features/resourcesync.go
New feature provided
Closes #775
> feat: sync route crd labels to apisix

- docs/en/latest/tutorials/mtls.md
link content：
The keys and certificates used in the examples [are here](https://github.com/apache/apisix-ingress-controller/tree/master/docs/en/latest/tutorials/mtls).
> docs: add example link.

- docs/en/latest/tutorials/the-hard-way.md
> docs: Update the-hard-way.md (#1581)

- docs/en/latest/tutorials/mtls.md
> docs: add example link. (#1582)

- CHANGELOG.md
> docs: add CHANGELOG for v1.6.0

- docs/en/latest/concepts/apisix_route.md
Fixes #1564 
Add a note mentioning how to enable the Plugins that are not enabled by default.
> docs: add note about enabling the Plugin

- docs/en/latest/deployments/ack.md
- docs/en/latest/deployments/aws.md
- docs/en/latest/deployments/azure.md
- docs/en/latest/deployments/gke.md
- docs/en/latest/deployments/k3s-rke.md
- docs/en/latest/deployments/kind.md
- docs/en/latest/deployments/kubesphere.md
- docs/en/latest/deployments/minikube.md
- docs/en/latest/deployments/tke.md
- docs/en/latest/tutorials/how-to-use-go-plugin-runner-in-apisix-ingress.md
- docs/en/latest/tutorials/manage-certificates-with-cert-manager.md
- docs/en/latest/tutorials/manage-ingress-certificates-with-cert-manager.md
- docs/en/latest/tutorials/proxy-grpc-service.md
Hi,
This PR is made according to [our discussion](https://github.com/apache/apisix-ingress-controller/issues/1435#issuecomment-1374964779)
Thank you.
> docs: update controller to use adminAPIVersion=v3

- docs/en/latest/getting-started.md
Part of #1597 
Add an example of the Gateway API to the "Getting started" guide.
> docs: add Gateway API example to the "Getting started" guide

- docs/en/latest/config.json
- docs/en/latest/tutorials/configure-ingress-with-gateway-api.md
- docs/en/latest/tutorials/proxy-the-httpbin-service.md
Part of #1597
Add a tutorial for using the Gateway API.
> docs: add tutorial for Gateway API

- powered-by.md
Thanks to the community, great job!
> docs: update prowered-by.md

- pkg/kube/apisix/apis/config/v2/types.go
- pkg/providers/apisix/translation/apisix_route.go
- pkg/types/apisix/v1/types.go
- samples/deploy/crd/v1/ApisixRoute.yaml
- test/e2e/suite-features/route_filter_func.go
close: #1532
Add support for `filter_func` for ApisixRoute
> feat: add support for filter_func for ApisixRoute

- docs/en/latest/concepts/annotations.md
> doc: add svc-namespace description to the annotations

- docs/en/latest/concepts/annotations.md
Co-authored-by: Navendu Pottekkat <navendupottekkat@gmail.com>
> [cherry-pick]doc: add svc-namespace description to the annotations (#1605)

- docs/en/latest/upgrade.md
> doc: update 1.6 upgrade guide

- .github/workflows/lint-checker.yml
- docs/en/latest/config.json
- docs/en/latest/references/v2.md
Use tools for automatic generation, eliminating the need for manual maintenance.
Currently, I only submit the final generated files, we need to merge them to see the effect.
> docs: using tool auto generate references

- .github/dependabot.yml
> chore: add AlinsRan to dependabot reviewer

- test/e2e/scaffold/scaffold.go
- test/e2e/suite-ingress/suite-ingress-resource/stream.go
Closes: https://github.com/apache/apisix-ingress-controller/issues/1438
> test(e2e): add stream tcp proxy with SNI test 

- samples/deploy/crd/v1/ApisixUpstream.yaml
- test/e2e/suite-ingress/suite-ingress-features/status.go
close: https://github.com/apache/apisix-ingress-controller/issues/1619
> fix: Add ApisixUpstream CRD status property

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/improve_docs.yml
- .github/ISSUE_TEMPLATE/performance_issue.yml
**Don't merge**
Fixes #1571 
Updates issue templates to add bug report, feature request, and documentation templates.
Waiting to add a template to report performance issues.
> chore: update issue templates

- .github/PULL_REQUEST_TEMPLATE
This PR adds new types in the pull request template since the ones provided currently do not cover all scenarios of pull requests. Should fix #1572 .
> Add more types in the pull request template

- .github/workflows/license-checker.yml
> ci: update license-checker

- docs/en/latest/tutorials/check-crd-status.md
I noticed a typo in the online documentation and wanted to fix it.
It turned out that the typo is already fixed on master, but I found a couple of more things to adjust.
> docs: small adjustments to Check CRD status tutorial

- docs/en/latest/tutorials/enable-authentication-and-restriction.md
In this document, the JWT section is misconfigured, so it needs to be changed: https://apisix.apache.org/docs/ingress-controller/next/tutorials/enable-authentication-and-restriction/#jwt-auth
> docs: fix jwtAuth configuration error in documents

- docs/en/latest/tutorials/proxy-grpc-service.md
First of all, the original image is no longer maintained and has not been updated for more than five years. When using tls communication, errors will occur. It may be that the protocol content has changed.
I will replace it with the official version 1.8.7, make it work properly.
The original image `quay.io/mhausenblas/gump:0.1` will cause the following errors:
> docs: update grpc proxy

- docs/en/latest/deployments/azure.md
Fixes typo in AKS(Azure) deployment guide.
> docs: fix typo in aks deployment guide

- docs/en/latest/tutorials/the-hard-way.md
Fix some bug and remove static (also outdated) in-doc resource.
Fixes #1686
> docs: update the-hard-way.md

- pkg/providers/apisix/translation/apisix_pluginconfig.go
- test/e2e/suite-chore/consistency.go
New feature provided
Closes #775
> feat: sync plugin-config labels to apisix

- docs/en/latest/tutorials/istio-egress-gateway
> docs: using APISIX Ingress as Istio egress gateway

- pkg/kube/apisix/apis/config/v2/types.go
- pkg/providers/apisix/apisix_plugin_config.go
- samples/deploy/crd/v1/ApisixPluginConfig.yaml
- test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
> feat: support ingressClass for ApisixPluginConfig

- .github/workflows/e2e-test-ci.yml
- Makefile
- test/e2e/e2e.go
- test/e2e/scaffold/k8s.go
- test/e2e/scaffold/scaffold.go
- test/e2e/suite-cluster/apisix_cluster_config.go
- test/e2e/suite-features/external-sd.go
- test/e2e/suite-features/external-service.go
- test/e2e/suite-features/global_rule.go
- test/e2e/suite-ingress/suite-ingress-features/ingress-class.go
fix:
* Incorrect  label
* Cluster level resource access is mutually exclusive
* Sleep pose
**Question**
https://github.com/apache/apisix-ingress-controller/actions/runs/4475046823/jobs/7864164247
https://github.com/apache/apisix-ingress-controller/actions/runs/4477968110/jobs/7873769689 
Ci is currently very unstable for three main reasons:
1. Opts.NamespaceLabel resources are mutually exclusive
-  **It may inject incorrect labels, resulting in incorrect configuration of the namespaceSelector and failure of the test case.**
2. ApisixClusterConfig resources are mutually exclusive: 
- **In concurrent scenarios, resources at the cluster level cannot be isolated through ns, which may result in resources from other use cases being incorrectly watched.**
3. Incorrect sleep posture.
- Creating …
> e2e: stability

- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/k8s-timer-ci.yml
- Makefile
There are some warning messages in CI 
```
coverage: [no statements]
You're using deprecated Ginkgo functionality:
=============================================
--ginkgo.slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.
To silence deprecations that can be silenced set the following environment variable:
ACK_GINKGO_DEPRECATIONS=2.9.0
```
> ci: Upgrade Ginkgo to latest version

- docs/en/latest/config.json
- docs/en/latest/tutorials/using-custom-plugins.md
Add new tutorial on using custom Plugins with APISIX Ingress.
> docs: add tutorial on using custom Plugins

- pkg/providers/ingress/translation/translator.go
- test/e2e/suite-ingress/suite-ingress-resource/ingress.go
> [cherry-pick] fix: panic at empty http spec (#1660)

- CHANGELOG.md
- Makefile
- releases/README.md
- releases/v1.6.1.toml
> chore: v1.6.1 release note

- docs/en/latest/deployments/openshift.md
> docs: Deploy to OpenShift

- docs/en/latest/plugins/traffic-split.md
> docs: add traffic-split plugin usage

- pkg/apisix/schema.go
- pkg/apisix/schema_test.go
This PR fixes the malformed URL bug pointed out in the issue #1771
> Fix malformed URL created in schemaClient

- pkg/apisix/cluster.go
> fix: error message typo

- .github/workflows/e2e-test-ci.yml
- Dockerfile
- test/e2e/scaffold/k8s.go
- test/e2e/scaffold/scaffold.go
- test/e2e/scaffold/test_backend.go
- test/e2e/suite-gateway/gateway_udproute.go
- test/e2e/suite-ingress/suite-ingress-resource/stream.go
- test/e2e/testdata/apisix-gw-config-v3.yaml
> fix(ci): udp forward failed and missing pigz

- .github/dependabot.yml
@Gallardot  helped us review a lot of PRs, I think we can add him as a default reviewer.
> chore: add Gallardot for deps reviewer

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/goimports-reviser.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .github/workflows/yamllint-checker.yml
- CHANGELOG.md
- Makefile
> chore: release v1.7.0

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/goimports-reviser.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .github/workflows/yamllint-checker.yml
- CHANGELOG.md
- Makefile
> chore: release v1.7.0 (#1952)

- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/k8s-timer-ci.yml
Currently the `ginkgo cli` version and the `ginkgo package` version are mismatched.
ref: https://github.com/apache/apisix-ingress-controller/actions/runs/6147275920/job/16678674762
> ci: update ginkgo version to 2.12.0

- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/goimports-reviser.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/k8s-timer-ci.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .github/workflows/yamllint-checker.yml
This is fiing some issues related to bad workflows (syntax error in `type` instead `types`. It also bumps actions versions to newest available. Additionally update ginko dependency which is causing CI to fail
> Fix workflows

- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/goimports-reviser.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .github/workflows/yamllint-checker.yml
> ci: remove the conditions for triggers

- .github/workflows/lint-checker.yml
> chore(ci): upgrade node version

- README.md
- docs/en/latest/composite.md
- docs/en/latest/config.json
- samples/deploy/composite.yaml
> fix: ingress-apisix version of deploy image tag and document (#1968)

- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/k8s-timer-ci.yml
- Makefile
This is solving issue with hardcoded version of Ginkgo module. There is strict dependency between tests in go using ginkgo package and local Ginkgo binary used for those tests. Currently after each update in dependencies CI start failing with log:
```sh
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
Ginkgo CLI Version:
2.12.0
Mismatched package versions found:
2.12.1 used by e2e
Ginkgo will continue to attempt to run but you may see errors (including flag
parsing errors) and should either update your go.mod or your version of the
Ginkgo CLI to match.
To install the matching version of the CLI run
go install github.com/onsi/ginkgo/v2/ginkgo
from a path that contains a go.mod file.  Alternatively you can use
go run …
```
> fix: ginko versions in e2e tests

- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/k8s-timer-ci.yml
- Makefile
- test/e2e/suite-annotations/websocket.go
- test/e2e/suite-features/websocket.go
- test/e2e/suite-gateway/gateway_httproute.go
- utils/kind-with-registry.sh
Currently, the default REGISTRY is `localhost:5000` in CI and Makefile, but it does not work on my local machine(MBP with Arm arch). I find if we change the `localhost` to `127.0.0.1`, it works well, so I created this PR to solve the issue to keep it compatible with MacOS.
> chore: support customize docker repository name

- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/k8s-timer-ci.yml
- Dockerfile
- Makefile
- test/e2e/suite-features/sync-delay.go
> chore: change the base image to distroless

- CHANGELOG.md
- Makefile
- releases/v1.7.1.toml
> chore: add v1.7.1 release note

- pkg/providers/ingress/translation/translator.go
- pkg/providers/ingress/translation/translator_test.go
- test/e2e/suite-ingress/suite-ingress-features/secret.go
- test/e2e/suite-ingress/suite-ingress-resource/ingress.go
> fix: create unique TLS object for each item in Ingress tls

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/goimports-reviser.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .github/workflows/yamllint-checker.yml
- CHANGELOG.md
- Makefile
- releases/v1.8.0.toml
> feat: add release notes for v1.8.0 release

- .asf.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/e2e-test-ci-v2-cron-dev.yml
- .github/workflows/e2e-test-ci-v2-cron.yml
- .github/workflows/e2e-test-ci.yml
- .github/workflows/goimports-reviser.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/license-checker.yml
- .github/workflows/lint-checker.yml
- .github/workflows/spell-checker.yml
- .github/workflows/unit-test-ci.yml
- .github/workflows/verify-codegen.yml
- .github/workflows/yamllint-checker.yml
- CHANGELOG.md
- Makefile
- releases/v1.8.0.toml
* feat: add release notes for v1.8.0 release
* apply suggestions
> feat: add release notes for v1.8.0 release (#2111)

- docs/en/latest/tutorials/external-service-discovery.md
> docs: clarify usage of external service discovery

- NOTICE
> chore: update NOTICE to 2024

- .github/dependabot.yml
> chore(ci): remove tao12345666333 and lingsamuel in reviewers

- docs/en/latest/tutorials/using-custom-plugins.md
- Fixing documentation for adding customPlugins and plugins since the placement is inside apisix config
https://artifacthub.io/packages/helm/apisix/apisix#values
> fix: placement for customPlugins and plugins config

- CHANGELOG.md
- pkg/apisix/cache/cache.go
- pkg/apisix/cache/memdb.go
- pkg/apisix/cache/noop_db.go
- pkg/apisix/nonexistentclient.go
- pkg/apisix/pluginconfig.go
- pkg/apisix/upstream.go
> fix: backport fix of deletion of references

- CHANGELOG.md
> chore: add release note for 1.8.2

- Makefile
> chore: update version in makefile for 1.8.2

- docs/en/latest/concepts/apisix_global_rule.md
> docs: correct yaml format in apisix_global_rule.md

- docs/en/latest/references/apisix_cluster_config_v2.md
Closes https://github.com/apache/apisix-ingress-controller/issues/1736
The `prefer_name` field already has test coverage.
> docs: add `prefer_name` to `ApisixClusterConfig/v2` spec

- docs/en/latest/concepts/apisix_global_rule.md
Wrong symbol in crd example for global rule
> fix: typo in apisixa_global_rule.md

- CHANGELOG.md
- pkg/providers/apisix/apisix_global_rule.go
Recently a customer faced an issue with the global rule in composite mode. This release fixes that issue.
> release: cherry pick commit and add changelog for release 1.8.3

- go.mod
- go.sum
- test/e2e/go.mod
- test/e2e/go.sum
- test/e2e/suite-chore/etcd_consistency.go
After the etcd=adapter upgrade, the bug which caused newer updates to be not seen after ingress restarts in etcd.enabled mode has been fixed.
This PR upgrades to newer adapter and adds e2e case.
> upgrade: etcd-adapter and add e2e test

- Makefile
> update version in Makefile

- Dockerfile
- Dockerfile.dev
- test/e2e/gatewayapi/gatewayproxy.go
> chore: remove useless example files in dockerfile

- CHANGELOG.md
- Makefile
- releases/v2.0.0.toml
> chore: v2.0.0-rc1 release

- docs/en/latest/config.json
> fix: doc broken links

- docs/en/latest/reference/example.md
Same as https://github.com/apache/apisix-ingress-controller/pull/2511 for master branch.
Fix #2510
> docs: fix indentation in reference doc (master)

- test/e2e/gatewayapi/gateway.go
fix: https://github.com/apache/apisix-ingress-controller/actions/runs/17122228802/job/48565669240
> fix(test): unstable controllername assertion

- api/v2/apisixupstream_types.go
- config/crd/bases/apisix.apache.org_apisixupstreams.yaml
- docs/en/latest/reference/api-reference.md
Correct description for externalNodes in the CRD docs.
> docs: correct description for externalNodes

- docs/en/latest/FAQ.md
- docs/en/latest/config.json
Add FAQ page addressing 3 questions.
> docs: add FAQ page

- test/e2e/crds/v2/route.go
> chore: remove redundant debug logging for metrics response

- .github/workflows/apisix-e2e-test.yml
- Makefile
- test/e2e/crds/v2/consumer.go
- test/e2e/testdata/ldap/cmd.sh
- test/e2e/testdata/ldap/docker-compose.yaml
> chore: backport ldap auth test

- api/adc/types.go
- api/v2/apisixupstream_types.go
- config/crd/bases/apisix.apache.org_apisixupstreams.yaml
- docs/en/latest/reference/api-reference.md
- docs/en/latest/upgrade-guide.md
- internal/adc/translator/apisixupstream.go
- internal/adc/translator/translator.go
- test/e2e/crds/v2/upstream.go
- test/e2e/scaffold/adc.go
The CRD feature is already supported in version 1.x, but has not been implemented in version 2.x.
> feat(apisixupstream): support healthcheck

- test/e2e/crds/v2/streamroute.go
> chore: add stream_route test for standalone

- api/adc/types.go
- config/rbac/role.yaml
- docs/en/latest/concepts/gateway-api.md
- internal/adc/translator/apisixroute.go
- internal/adc/translator/tcproute.go
- internal/adc/translator/udproute.go
- internal/controller/indexer/indexer.go
- internal/controller/udproute_controller.go
- internal/controller/utils.go
- internal/manager/controllers.go
- internal/provider/apisix/provider.go
- internal/provider/apisix/status.go
- internal/types/k8s.go
- test/e2e/framework/manifests/ingress.yaml
- test/e2e/gatewayapi/udproute.go
- test/e2e/scaffold/scaffold.go
> feat(gateway-api): add support for UDPRoute

- docs/en/latest/upgrade-guide.md
Clarify support for Ingress Annotations.
> docs: clarify support for Ingress Annotations
