doc/deploy/deploy.md
doc/dev/develop.md
samples/deploy/deployment/ingress-controller.yaml

When i use `kubectl apply -f ingress-controller.yaml`, i get following error:
```shell
[root@k8s-master eplat-yamls]# kubectl apply -f ingress-controller.yaml 
The Deployment "ingress-controller" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"apisix", "tier":"backend"}: `selector` does not match template `labels`
```
Must modify the `ingress-controller.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: ingress-controller
namespace: cloud
spec:
minReadySeconds: 5
replicas: 1
selector:
matchLabels:
app: apisix # Change 'ingress-controller' to 'apisix'
tier: backend
strategy:
rollingUpdate:
maxSurge: 50%
maxUnavailable: 1
type: RollingUpdate
template:
metadata:
annotations: {}
labels:
app: apisix
tier: backend
spec:
hostNetwork: true …
```

fix: `ingress-controller.yaml` 

---

cmd/cmd.go
cmd/ingress/ingress.go
conf/errno.go
conf/init.go
log/log.go
main.go
pkg/ingress/apisix/annotation.go
pkg/ingress/apisix/plugin.go
pkg/ingress/apisix/route.go
pkg/ingress/apisix/route_test.go
pkg/ingress/apisix/service.go
pkg/ingress/apisix/upstream.go
pkg/ingress/apisix/upstream_test.go
pkg/ingress/controller/apisix_route.go
pkg/ingress/controller/apisix_service.go
pkg/ingress/controller/apisix_upstream.go
pkg/ingress/controller/controller.go
pkg/ingress/controller/endpoint.go
pkg/ingress/controller/store/store.go
pkg/ingress/controller/watch.go
pkg/ingress/endpoint/ep.go
pkg/log/default_logger.go
pkg/log/default_logger_test.go
pkg/log/logger.go
pkg/log/logger_test.go
pkg/log/options.go
pkg/route.go
pkg/scheduler.go

Files are filtered by:
```shell
find . -name "*.go"
```

chore: add Apache License header in each go source file.

---

samples/deploy/deployment/ingress-controller.yaml

Closing https://github.com/apache/apisix-ingress-controller/issues/55.
We will use this image until we release the 0.1.0 version.

fix: use the temporary image

---

cmd/ingress/ingress.go
go.mod
go.sum
pkg/ingress/apisix/tls.go
pkg/ingress/apisix/tls_test.go
pkg/ingress/controller/apisix_route.go
pkg/ingress/controller/apisix_tls.go
pkg/ingress/controller/controller.go
samples/deploy/crd/v1beta1/ApisixTls.yaml
samples/deploy/rbac/apisix_view_clusterrole.yaml

feat: support TLS

---

docs/develop.md

Fixing https://github.com/apache/apisix-ingress-controller/issues/30.

doc: update develop.md

---

cmd/ingress/ingress.go
go.mod
pkg/metrics/prometheus.go
pkg/metrics/prometheus_test.go

Abstract a metrics collector `metrics.Collector` and implement it with a Prometheus collector.
The collector is created in `cmd/ingress.Run`, which will be moved to the ingress controller after we have an unified ingress controller object.
Metrics are not used except the `Collector.ResetLeader` (which is always true since we don't use the leader election), others will be used during the refactoring.

chore: add some metrics

---

conf/config-default.json
conf/config-default.yaml
pkg/config/config.go
samples/deploy/configmap/apisix-ingress-cm.yaml

As Resync has been set, change the default value to 6 hours.

chore: change default resync period to 6 hours

---

Makefile
cmd/ingress/ingress.go
conf/config-default.yaml
pkg/config/config.go
pkg/config/config_test.go
pkg/ingress/controller/apisix_route.go
pkg/ingress/controller/apisix_service.go
pkg/ingress/controller/apisix_tls.go
pkg/ingress/controller/apisix_upstream.go
pkg/ingress/controller/controller.go
pkg/ingress/controller/endpoint.go
test/e2e/ingress/namespace.go
test/e2e/ingress/resourcepushing.go
test/e2e/scaffold/crd.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/scaffold.go

Support to filter namespaces by specifying `--app-namespace` (multiple times if necessary) or adding `app_namespace` in configuration file. By default all namespaces will be watched.
What's more, after this PR is merged, e2e test cases can be run in parallel.
Closing #139

chore: namespaces filtering

---

Makefile

___
- Description
- How to fix?
___
Customize the concurrency of e2e cases, the performance if the single node minikube cluster is bad, by default we set the concurrency to 1, i.e.g run the test suites sequentially.
___

chore: customize the concurrency of e2e cases.

---

charts/ingress-apisix/templates/deployment.yaml
cmd/ingress/ingress.go
conf/config-default.yaml
pkg/config/config.go
pkg/config/config_test.go
pkg/ingress/controller/controller.go
samples/deploy/deployment/ingress-controller.yaml
test/e2e/ingress/namespace.go
test/e2e/ingress/resourcepushing.go
test/e2e/ingress/sanity.go
test/e2e/scaffold/httpbin.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/scaffold.go

#85 
___
- Description
- How to fix?
___
___

feat: controller leader election

---

charts/ingress-apisix/templates/configmap.yaml
docs/deployments/aws.md
docs/install.md

___
- Description
- How to fix?
___
___

doc: add doc about run on aws eks

---

docs/deployments/aws.md
docs/deployments/azure.md
docs/deployments/gke.md
docs/deployments/k3s.md
docs/deployments/minikube.md

___
- Description
- How to fix?
___
___

doc: add document to explain how to run on GKE

---

test/e2e/endpoints/endpoints.go

The image apache/apisix:dev was updated these two days, the status code when upstream is not available was changed from 502 to 503, so the e2e case should also be adjusted.

fix: broken e2e test case

---

pkg/ingress/controller/controller.go

___
- Description
Start two controller, A first became leader and add cluster, and B later became leader,
then B stop and A became leader again, this time A will can not working because of add duplicated cluster.
- How to fix?
Skip ErrDuplicatedCluster when rebecame leader.

fix: skip ErrDuplicatedCluster when rebecame leader

---

README.md
pkg/ingress/controller/controller.go
pkg/ingress/controller/ingress.go

___
- Description
fix https://github.com/apache/apisix-ingress-controller/issues/293

fix: use networking informer instead of extensions

---

cmd/ingress/ingress.go
conf/config-default.yaml
pkg/config/config.go
pkg/ingress/controller/controller.go
pkg/ingress/controller/ingress.go
pkg/ingress/controller/ingress_test.go
pkg/kube/ingress.go
pkg/kube/translation/ingress.go
pkg/kube/translation/ingress_test.go
test/e2e/ingress/ingress.go

#313 
___
- Description
- How to fix?
___
___

fix: make ingress controller compatible with ingress.extensions/v1beta1

---

pkg/kube/apisix/apis/config/v2alpha1/types.go
pkg/seven/state/solver.go
test/e2e/README.md
test/e2e/e2e.go
test/e2e/plugins/fault_injection.go
test/e2e/plugins/redirect.go
test/e2e/plugins/uri_blocker.go
test/e2e/scaffold/scaffold.go

___
- Description
- How to fix?
___
___

test: add e2e test cases for redirect, uri-blocker and fault-injection plugins

---

test/e2e/plugins/limit_count.go

___
- Description
- How to fix?
___
___

test: add e2e test cases for limit-count plugin

---

pkg/apisix/resource.go
pkg/apisix/route.go
pkg/apisix/upstream.go
test/e2e/ingress/resourcepushing.go
test/e2e/scaffold/k8s.go

___
- Description
- How to fix?
___
**add name field when create route and upstream, in order to fit apisix-dashboard.
the name field is a required field in the apisix-dashboard's route and upstream.**
___

fix: add name field when create route and upstream

---

test/e2e/plugins/cors.go

___
- Description
- How to fix?
___
___

test: add e2e test cases for cors plugin

---

pkg/apisix/cluster.go
pkg/apisix/route.go
pkg/apisix/upstream.go
test/e2e/plugins/cors.go
test/e2e/plugins/echo.go
test/e2e/plugins/fault_injection.go
test/e2e/plugins/limit_count.go
test/e2e/plugins/redirect.go
test/e2e/plugins/request_id.go
test/e2e/plugins/uri_blocker.go

#351
___
- Description
- How to fix?
___
___

fix: use put (instead of patch) as the method when updating resources.

---

pkg/apisix/resource.go
pkg/apisix/route.go
pkg/kube/translation/apisix_route.go
pkg/kube/translation/util.go
pkg/kube/translation/util_test.go
pkg/types/apisix/v1/types.go
test/e2e/features/remote_addrs_match.go

___
- Description
- How to fix?
___
___

fix: pass remote_addrs to APISIX

---

samples/deploy/crd/v1beta1/ApisixRoute.yaml

___
- Description
- How to fix?
___
___

feat: schema for apisixroute

---

pkg/ingress/ingress.go

get extensions/v1beta1 object when group version is extensions/v1beta1
fix: #365
#365 
___
- Description
get extensions/v1beta1 object via networking/v1beta1 interface, it's of course not found
- How to fix?
handle ingress in extensions/v1beta1 correctly

fix: correctly handle ingress in extensions/v1beta1 version

---

test/e2e/plugins/ip-restriction.go

This PR added some e2e test cases to cover the usage of `ip-restriction` plugin.

test: add e2e test cases for ip-restriction plugin

---

pkg/apisix/global_rule.go
pkg/apisix/route.go
pkg/apisix/ssl.go
pkg/apisix/stream_route.go
pkg/apisix/upstream.go

fix: Avoid retrying caused by 404 when deleting cache 

---

docs/en/latest/references/apisix_route_v2alpha1.md

Change `remote_addrs` field to `remoteAddrs` to comply with naming convention.

fix: typo in apisix_route_v2alpha1.md

---

pkg/ingress/apisix_route.go
pkg/ingress/apisix_tls.go
pkg/ingress/apisix_upstream.go
pkg/ingress/controller.go
pkg/ingress/status.go
pkg/kube/init.go

___
- Description
- How to fix?
___
___

chore: refactor the structures of kube clients, shared index informer factories

---

pkg/ingress/endpoint.go

___
- Description
- How to fix?
___
- Some endpoints doesn't have corresponding services, currently endpoint controller will log massive warning continuously

chore: optimize log message when the endpoint does not have a corresponding service

---

.github/workflows/cancel-workflow.yml
.gitmodules

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
The Github Actions - cancel workflow have already been applied in apisix and dashboard, and it works well, so try to also import it here.
> We always wait for CI queue time, and we always trying to reduce waiting time. Here is another method to achieve it.
> 
> The method is that whenever a new commit added to PR, the previous running CI could be canceled since it is of no use. This could be achieved by using Github API, find the workflow on the same branch but with different SHA. And we could achieve this with [potiuk/cancel-workflow-runs](https://github.com/potiuk/cancel-workflow-runs) which is also [used in Apache Airflow](https://github.com/apache/airflow/blob/master/.github/workflows/build-images-workflow-run.yml).
> 
> To bypass the …

ci: cancel duplicate workflow to reduce CI queue time

---

.github/workflows/e2e-test-ci.yml
.gitmodules

Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
Ref: https://github.com/apache/apisix/issues/4341
Use github official argument to cancel duplicate workflows, to replace deprecated `cancel-workflow-runs`.
Tested for push and PR from [original repo](https://github.com/Yiyiyimu/GithubActionsTest/pull/8) and [forked repo](https://github.com/Yiyiyimu/GithubActionsTest/pull/9)

ci: use concurrency to cancel workflow

---

Makefile

* Why submit this pull request?
To keep the default version of apisix-ingress-controller in Makefile up-to-date (1.0.0).
* Related issues
#553

chore: update default version in Makefile

---

install.md

Add more instructions on how to modify config files and which parameter need to be tweaked in the section Kustomize Support.

docs: clarify installation by Kustomize

---

samples/deploy/configmap/apisix-ingress-cm.yaml
samples/deploy/deployment/ingress-controller.yaml

___
- Description
Installation by Kustomize is not working unless correct configuration of several parameters. The default value of `apisix.base_url` is not a correct APISIX Admin adress. Also, `apisix.admin_key` is missing so that one would get _401 Authorization Required_ error when invoking APISIX Admin API.
- How to fix?
Update default values in config file to make the installation of apisix-ingress-controller by Kustomize ready to use.
* update the default version of apisix-ingress-controller container image to keep it up-to-date
* update `apisix.base_url` to send requests to the correct APISIX address
* add `apisix.admin_key` to configure APISIX Admin API access token. This avoids _401 Authenticaion Required_ error when invoking …

fix: update config of installation by Kustomize

---

.golangci.yml
pkg/apisix/apisix.go
pkg/apisix/cache/cache.go
pkg/apisix/cache/memdb.go
pkg/apisix/cache/memdb_test.go
pkg/apisix/cache/schema.go
pkg/apisix/cluster.go
pkg/apisix/cluster_test.go
pkg/apisix/nonexistentclient.go
pkg/apisix/plugin.go
pkg/apisix/plugin_test.go
pkg/apisix/resource.go
pkg/apisix/resource_test.go
pkg/apisix/schema.go
pkg/apisix/schema_test.go
pkg/apisix/ssl_test.go
pkg/apisix/stream_route_test.go
pkg/ingress/apisix_cluster_config.go
pkg/ingress/controller.go
pkg/kube/translation/ingress_test.go
pkg/kube/translation/plugin_test.go
pkg/kube/translation/translator_test.go
pkg/types/apisix/v1/types.go
test/e2e/scaffold/k8s.go

___
- Implement schema API for getting plugin's schema from APISIX.

feat: implement schema API

---

pkg/kube/apisix/apis/config/v2alpha1/types.go
pkg/kube/apisix/apis/config/v2beta1/types.go

- Description
Using `clientset` to create `ApisixRoute` will get error `spec.http.backend: Invalid value: "null"` when only set `backends`
- Related issues:
#621
- How to fix?
adding `omitempty` to `not-required` field

bugfix: add tag omitempty for the fields in some data structures

---

docs/en/latest/config.json
docs/en/latest/practices/mtls/route.yaml
docs/en/latest/practices/the-hard-way.md
docs/en/latest/references/apisix_cluster_config.md
docs/en/latest/references/apisix_route_v1.md

docs: ApisixRoute v2alpha1 is deprecated

---

CHANGELOG.md
Makefile
docs/en/latest/getting-started.md
releases/v1.2.0.toml

Release vote for Apache apisix-ingress-controller 1.2.0 has PASSED and closed.
https://lists.apache.org/thread.html/r8e3ac90fdbb4e64487105a2b34f042f8617fd60b60f22b18fcf8ce47%40%3Cdev.apisix.apache.org%3E

chore: release v1.2.0

---

go.sum
pkg/ingress/manifest.go
pkg/kube/translation/ingress.go
test/e2e/go.mod
test/e2e/ingress/ingress.go

closes #586
___
- Support ingress v1 TLS field

feat: support TLS for ingress v1

---

docs/en/latest/config.json

___
- Description
currently these two articles have not been indexed in our [ingress controller docs](https://apisix.apache.org/docs/ingress-controller/practices/index)
* https://apisix.apache.org/docs/ingress-controller/practices/check-crd-status/
* https://apisix.apache.org/docs/ingress-controller/practices/mtls/
- How to fix?
update config.json in docs dir to include these two articles.

docs: update index of practices docs for website

---

test/e2e/scaffold/k8s.go

___
- Description
If the `count` field is string, its value is greater than actual value by 1.
- How to fix?
Decrease `count` if its type is string.

fix: e2e failure due to count returned by APISIX

---

Makefile
docs/en/latest/practices/the-hard-way.md
pkg/api/validation/apisix_route_test.go
test/e2e/scaffold/ingress.go

fix: add initContainers to verify if apisix is ready

---

pkg/apisix/cluster.go
pkg/ingress/apisix_consumer.go
pkg/ingress/apisix_tls.go
pkg/ingress/controller.go
pkg/ingress/endpoint.go
pkg/ingress/endpointslice.go
pkg/ingress/secret.go
pkg/metrics/prometheus.go
pkg/metrics/prometheus_test.go

___
add two Promethues metrics for apisix-ingress-controller:
***
HELP apisix_ingress_controller_check_cluster_health_success Number of cluster health check operations
TYPE apisix_ingress_controller_check_cluster_health_success counter
Label:
* controller_class
* controller_namespace
* controller_pod
* name (cluster name)
***
HELP apisix_ingress_controller_sync_success Number of success sync operations 
TYPE apisix_ingress_controller_sync_success counter  
Labels:
* controller_class
* controller_namespace
* controller_pod
* resource ( cache, schema, ssl, endpoint, consumer)
* result (success, failure)
***
Show in Prometheus:
```
apisix_ingress_controller_check_cluster_health{controller_namespa …
```

feat: add metric 'check_cluster_health_total' and 'sync_operation_total'

---

go.mod
go.sum
pkg/apisix/schema.go
test/e2e/go.sum
test/e2e/ingress/webhook.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/scaffold.go
test/e2e/testdata/webhook-create-signed-cert.sh

___
- Description
It will occur errors when webhook is disabled but the controller pod tried to mount the volume.
- How to fix?
Add a placeholder in deployment template, decide whether to populate the `volumeMount` or not according to whether the webhook is enabled.

Remove volumeMounts when webhook is disabled

---

docs/en/latest/upgrade.md
policy/base.rego

___
- Description
- How to fix?
___
___

docs: add upgrade guide

---

pkg/kube/apisix/apis/config/v2alpha1/types.go

___
- Description
In the ApisixRoute CRD: 
So the field `value` and `set` can't appear at the same time
But the golang data structure will be marshal to `value: null` or `set: null`, this will cause CRD checking error
- How to fix?
Adding tag `omitempty` to this field

Bugfix: add tag omitempty for the fields in this data structure ApisixRouteHTTPMatchExpr

---

test/e2e/ingress/stream.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/k8s.go

Use independent dns service for UDP e2e test, avoid create resource in kube-system namespace
#751

fix: use independent dns service for UDP e2e test

---

docs/en/latest/deployments/ack.md
docs/en/latest/deployments/aws.md
docs/en/latest/deployments/azure.md
docs/en/latest/deployments/gke.md
docs/en/latest/deployments/k3s-rke.md
docs/en/latest/deployments/kubesphere.md
docs/en/latest/deployments/minikube.md
docs/en/latest/deployments/tke.md
docs/en/latest/practices/manage-certificates-with-cert-manager.md
docs/en/latest/practices/manage-ingress-certificates-with-cert-manager.md
docs/en/latest/practices/proxy-grpc-service.md

In the latest version we have introduced a new configuration item.
When users want to install them into different namespaces through Helm,
they need to specify it.
___
- Description
- How to fix?
___
___

docs: Customize the namespace used for installation

---

docs/en/latest/practices/proxy-the-httpbin-service.md

Updation required in the in the document ( https://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service/ ) describing an example in the  installation instructions for Minikube ( https://apisix.apache.org/docs/ingress-controller/deployments/minikube ).
@tokers

docs: update proxy-the-httpbin-service.md

---

pkg/config/config.go
pkg/config/config_test.go
test/e2e/config/config.go
test/e2e/config/manifests.go
test/e2e/go.mod
test/e2e/scaffold/ingress.go
test/e2e/scaffold/k8s.go
test/e2e/scaffold/scaffold.go

Sorry, the https://github.com/apache/apisix-ingress-controller/pull/713 closed because I wrongly rebase the upstream code, so now I have initiated a new PR. e2e has been added, can be review again
#710

feat: support environment variable in config file

---

pkg/kube/translation/apisix_route.go

___
- Description
The controller will set default timeout 60s to the Apisix Route if not assigned `timeout` in the ApisixRoute CRD
And The Apisix Route timeout  will overwrite the timeout option which set in Upstream configuration.
- How to fix?
Keeping the original logic， not assign default timeout to the Apisix Route

bug: Remove route timeout default value

---

pkg/ingress/apisix_cluster_config.go
pkg/ingress/apisix_consumer.go
pkg/ingress/apisix_route.go
pkg/ingress/apisix_tls.go
pkg/ingress/apisix_upstream.go
pkg/ingress/endpoint.go
pkg/ingress/endpointslice.go
pkg/ingress/ingress.go
pkg/ingress/namespace.go
pkg/ingress/secret.go

#759 
___
- How to fix?
This bug is due to a `workqueue` shared under the same resource, and a `ratelimit` mechanism is added to this `workqueue`, but we only need to add the `ratelimit` when retrying fails, and when normal resource changes, we should immediately add the `workqueue` to be processed .
The new k8s event does not need to use the rate limit.

fix: If resource synchronization retry occurs, other events of the same resource will be blocked.

---

pkg/api/validation/utils.go
pkg/api/validation/utils_test.go
pkg/ingress/compare.go
pkg/ingress/controller.go
pkg/types/labels.go
pkg/types/labels_test.go

fix: ingress do not watching any namespace when namespaceSelector is empty

---

docs/en/latest/concepts/annotations.md
pkg/kube/translation/annotations/cors.go
pkg/kube/translation/annotations/iprestriction.go
pkg/kube/translation/annotations/redirect.go
pkg/kube/translation/annotations/rewrite.go
pkg/kube/translation/annotations/types.go
pkg/kube/translation/ingress.go
pkg/kube/translation/ingress_test.go
test/e2e/ingress/ingress.go

- Related issues #768 
___
- support a new annotation `k8s.apisix.apache.org/use-regex` which to change path behavior using apisix's vars

feat: support regex in path

---

pkg/ingress/status.go

___
- Description
When updating the status, it should carry its generation
- How to fix?
___
___

fix: ingress LB status records

---

docs/en/latest/development.md
utils/kind-with-registry.sh

Specify the K8S cluster version used for the test. To avoid CI failure due to inconsistent local environment version.

chore: specify the K8S cluster version used for the test

---

pkg/ingress/ingress.go

fix: some wrong or invalid logs

---

pkg/types/apisix/v1/types.go

The schema of APISIX consumer doesn't allow the  character `-`, so we need to replace `-` to `_`.
APISIX schema def：https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L679
fix #752

fix: consumer name contain "-"

---

pkg/ingress/compare.go

chore: update ingress/comapre.go watchingNamespac v2beta1 to v2beta3

---

cmd/ingress/ingress.go
pkg/ingress/controller.go
test/e2e/ingress/sanity.go

Ensure that the lease can be actively released before program shutdown to reduce the time required for failover

feat: ensure that the lease can be actively released before program shutdown to reduce the time required for failover

---

cmd/ingress/ingress.go
docs/en/latest/development.md
docs/en/latest/practices/proxy-the-httpbin-service-with-ingress.md
docs/en/latest/practices/proxy-the-httpbin-service.md

fix typo in development.md
fix typo in development.md

rename command line options and update doc

---

Makefile
pkg/apisix/plugin.go
pkg/ingress/status.go

* pin the image of APISIX to stable version
* using the new plugin list API
* fix ApisixClusterConfig status logic
fix: #857

fix: ApisixClusterConfig e2e test case

---

pkg/ingress/apisix_consumer.go
pkg/ingress/apisix_pluginconfig.go
pkg/ingress/apisix_route.go
pkg/ingress/apisix_tls.go
pkg/ingress/apisix_upstream.go
pkg/ingress/compare.go
pkg/ingress/controller.go
pkg/ingress/endpoint.go
pkg/ingress/endpointslice.go
pkg/ingress/gateway.go
pkg/ingress/ingress.go
pkg/ingress/namespace.go
pkg/ingress/pod.go
pkg/ingress/pod_test.go
pkg/ingress/secret.go

Fixes #816 
I couldn't find a stable way to reproduce this issue without changing the code, so there is no e2e test.
The only case this PR addresses is the error not found. Please add other cases if necessary.
If anyone else wants to reproduce this issue, please postpone the Create/Update events (example: wrap the function in a goroutine and add a time.Sleep at the beginning).

fix: endless retry if namespace doesn't exist

---

pkg/apisix/cluster.go
pkg/apisix/plugin_test.go

bug fix https://github.com/apache/apisix-ingress-controller/issues/883
the response body is JSON with unknown field names but not a string slice.

fix json unmarshal error when list plguins

---

docs/en/latest/practices/the-hard-way.md

docs: fix #887

---

pkg/ingress/pod.go
pkg/ingress/pod_test.go

`onUpdate` will get pod update event every `resync_interval` seconds/hours. It's unnecessary.

fix: filter useless pod update event

---

pkg/kube/translation/ingress.go

In the past, we used host + path directly to form its route name for readability,
but this method can cause problems in some scenarios.
For example, the generated name is too long.
The current APISIX limit its maximum length to 100.
We will construct the following structure for easy reading and debugging.
`ing_namespace_ingressName_id`
fix #781

chore: shorten the route name for Ingress transformations

---

pkg/ingress/apisix_tls.go
pkg/ingress/endpoint.go
pkg/ingress/endpointslice.go
pkg/ingress/secret.go
pkg/ingress/status.go

fix https://github.com/apache/apisix-ingress-controller/issues/806#issuecomment-1059945155

fix: fix up ep resourceVersion comparison and clean up

---

Makefile
test/e2e/README.md
test/e2e/scaffold/apisix.go
test/e2e/scaffold/etcd.go
test/e2e/scaffold/httpbin.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/scaffold.go
test/e2e/scaffold/test_backend.go

Solved [#880](https://github.com/apache/apisix-ingress-controller/issues/880)

feat: support custom registry for e2e test

---

pkg/ingress/apisix_cluster_config.go
pkg/ingress/apisix_consumer.go
pkg/ingress/apisix_pluginconfig.go
pkg/ingress/apisix_route.go
pkg/ingress/apisix_tls.go
pkg/ingress/apisix_upstream.go
pkg/ingress/endpoint.go
pkg/ingress/endpointslice.go
pkg/ingress/gateway.go
pkg/ingress/ingress.go
pkg/ingress/secret.go

fix: controller err handler should ignore not found error

---

pkg/ingress/apisix_route.go

fix: ApisixRouteEvent type assertion

---

pkg/ingress/compare.go
pkg/ingress/namespace.go
test/e2e/ingress/namespace.go
test/e2e/ingress/sanity.go
test/e2e/scaffold/httpbin.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/scaffold.go

fix https://github.com/apache/apisix-ingress-controller/issues/908

fix: watch all namespaces by default

---

docs/en/latest/deployments/kind.md

doc: add doc about installing apisix ingress with kind

---

docs/en/latest/practices/the-hard-way.md

Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Update the doc of hard way. 
Fixes #938

docs: update the hard way.

---

pkg/ingress/ingress.go

Fix https://github.com/apache/apisix-ingress-controller/issues/869
Since the ingress update event handler is not filtered according to the watching namespaces, and our e2e uses two ginkgo nodes, it will cause the lb status test case to be interfered with the ingress controller in other test cases. This is why e2e is unstable as described in https://github.com/apache/apisix-ingress-controller/issues/869.

fix: ingress update event handler not filter by watching namespaces

---

.github/actions/e2e/action.yaml
.github/workflows/e2e-test-ci.yml
Makefile
test/e2e/README.md
test/e2e/suite-annotations/iprestriction.go
test/e2e/suite-annotations/rewrite.go
test/e2e/suite-endpoints/endpoints.go
test/e2e/suite-features/retries.go
test/e2e/suite-features/route_match_exprs.go
test/e2e/suite-ingress/ingress.go
test/e2e/suite-ingress/sanity.go
test/e2e/suite-ingress/ssl.go
test/e2e/suite-ingress/status.go
utils/check-e2e-names.sh

In #949 we use `ginkgo --focus` to run test cases in parallel, but some newly added cases may not follow the naming convention. So we need to add a pre-check to avoid some E2E cases not running.
Tested on Linux:

Add a pre-check for E2E tests

---

pkg/kube/apisix/apis/config/v2beta3/types.go

fix ApisixConsumerBasicAuthValue password-yaml field error

---

.github/workflows/dependency-review.yml

>You can use the Dependency Review GitHub Action in your repository to enforce dependency reviews on your pull requests. The action scans for vulnerable versions of dependencies introduced by package version changes in pull requests, and warns you about the associated security vulnerabilities. This gives you better visibility of what's changing in a pull request, and helps prevent vulnerabilities being added to your repository. 
xref: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

ci: add dependency-review

---

test/e2e/scaffold/k8s.go
test/e2e/suite-plugins/serverless.go

Add e2e test for serverless plugin!

feat: add e2e test for serverless plugin

---

test/e2e/scaffold/k8s.go

ref: https://github.com/apache/apisix-ingress-controller/issues/969

refactor: encapsulate functions to reuse code

---

test/e2e/suite-plugins/referer-restriction.go

The original e2e testing of the referer-restriction plugin was not perfect, and the purpose of this PR is to improve the testing of the plugin.

feat: improve the e2e test of referer-restriction plugin

---

docs/assets/other/json/apisix-ingress-controller-grafana.json
pkg/metrics/prometheus.go
pkg/metrics/prometheus_test.go

Fix: https://github.com/apache/apisix-ingress-controller/issues/1005
rename metrics `apisix_bad_status_codes` to `apisix_status_codes`, as all the status codes are recorded here.

feat: modify metrics name `apisix_bad_status_codes` to `apisix_status_codes`

---

pkg/kube/apisix/apis/config/v2/types.go
samples/deploy/crd/v1/ApisixRoute.yaml
samples/deploy/crd/v1/ApisixTls.yaml
test/e2e/scaffold/scaffold.go
test/e2e/scaffold/ssl.go
test/e2e/suite-features/consumer.go
test/e2e/suite-features/scheme.go
test/e2e/suite-ingress/ingress.go
test/e2e/suite-ingress/ssl.go
test/e2e/suite-ingress/upstream_tls.go

e2e-test: add e2e tests and CRDs for ApisixTls v2

---

docs/en/latest/references/apisix_pluginconfig.md
docs/en/latest/references/apisix_route_v2beta3.md

doc: paraphrasing some descriptions about plugins

---

docs/en/latest/concepts/annotations.md
docs/en/latest/concepts/apisix_route.md
docs/en/latest/design.md
docs/en/latest/practices/mtls.md
docs/en/latest/practices/the-hard-way.md

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

docs: correct typo & link

---

pkg/kube/apisix/apis/config/v2/types.go
pkg/kube/apisix/apis/config/v2beta2/types.go
pkg/kube/apisix/apis/config/v2beta3/types.go

I'm currently doing some work to migrate kong's configuration to apisixroute, when marshaling `github.com/apache/apisix-ingress-controller/pkg/kube/apisix/apis/config/v2beta3.ApisixRoute` object,  the output of `keyAuth` field is `keyauth`.
So when I applied the generated manifests to apiserver, action failed because of CRD's Scheme verification.

fix: fix tag for keyAuth field

---

.github/workflows/stale.yml

chore: enable stale GitHub action

---

Makefile

issue: https://github.com/apache/apisix-ingress-controller/issues/1110
Update Makefile's verify-mdlint. Ignore CHANGELOG.md.

fix: update Makefile verify-mdlint

---

pkg/apisix/pluginconfig.go
pkg/apisix/upstream.go

For resources that will be referenced such as Upstream or PluginConfig,
when deleting, we need to check whether it is being referenced through
the cache first.
The delete operation will only be performed if the cache confirms that
it is not referenced.
fixes: https://github.com/apache/apisix-ingress-controller/issues/1122

fix: verify through the cache first, then delete

---

.github/workflows/e2e-test-ci.yml
Makefile
test/e2e/README.md
test/e2e/scaffold/scaffold.go

Related [issue](https://github.com/apache/apisix-ingress-controller/issues/1138)
Add environment variable `E2E_ENV` to indicate e2e-test environment. If test case failed and `E2E_ENV=dev`, related resources will not be deleted.

test: keep namespace when test failed in dev mod

---

pkg/ingress/apisix_route.go
pkg/ingress/utils/manifest.go
test/e2e/suite-chore/consistency.go

ref: 
* #1165 
* #1186 
When translating old objects, translateupstream needs to parse the latest services, which will lead to data inconsistency. Thus, retry and data inconsistency are caused.
Implements an function responsible for converting old objects
1. Get route object from cache.
2. Using route to construct Upstream and PluginConfig.
3. Compare and write APISIX.

fix: translate error of old ApisixRoute

---

docs/en/latest/FAQ.md

docs: fix dead link

---

pkg/apisix/resource_test.go
pkg/types/apisix/v1/types.go

* #712 
* #1218
**Question:** At present, the implementation only supports the conversion of array types.
**Resolved:** Add conversion of object type.

fix: nodes convert failed

---

docs/en/latest/config.json
docs/en/latest/deployments/ack.md
docs/en/latest/getting-started.md

Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
Updates the "Getting started" page. Also updates the ACK installation. Once these changes are approved, it will be propagated to other installation docs as well. Also rearranges installation to the top.

docs: update "Getting started" guide

---

pkg/providers/apisix/apisix_cluster_config.go
pkg/providers/apisix/apisix_upstream.go
pkg/providers/k8s/endpoint/endpointslice.go

fix: object type should be apisix_upstream and endpointslice and apisix_cluster_config

---

docs/en/latest/config.json
docs/en/latest/deployments/aws.md
docs/en/latest/deployments/azure.md
docs/en/latest/deployments/gke.md
docs/en/latest/deployments/k3s-rke.md
docs/en/latest/deployments/kind.md
docs/en/latest/deployments/kubesphere.md
docs/en/latest/deployments/minikube.md
docs/en/latest/deployments/tke.md

Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
Updates installation docs and rearranges it.

docs: update installation guide

---

pkg/api/validation/utils.go
pkg/api/validation/utils_test.go
pkg/providers/k8s/namespace/namespace_provider.go
test/e2e/scaffold/ingress.go
test/e2e/scaffold/k8s.go
test/e2e/scaffold/scaffold.go
test/e2e/suite-ingress/suite-ingress-features/namespace.go

* When all namespace do not have  labels(namespace_selector), all resources will be monitored, and the namespace_selector function will not be available.
e2e-test:
* **[un-label]** When restarting, all ns without labels will be monitored
* **[ingress-controller restart]** When restarting, all ns without labels will be monitored

fix: namespace_selector invalid when restarting

---

test/e2e/scaffold/scaffold.go

```go
func (s *Scaffold) afterEach() {
defer ginkgo.GinkgoRecover()
if ginkgo.CurrentSpecReport().Failed() {
if os.Getenv("E2E_ENV") == "ci" {
// dump and delete related resource
_, _ = fmt.Fprintln(ginkgo.GinkgoWriter, "Dumping namespace contents")
output, _ := k8s.RunKubectlAndGetOutputE(ginkgo.GinkgoT(), s.kubectlOptions, "get", "deploy,sts,svc,pods")
if output != "" {
_, _ = fmt.Fprintln(ginkgo.GinkgoWriter, output)
}
output, _ = k8s.RunKubectlAndGetOutputE(ginkgo.GinkgoT(), s.kubectlOptions, "describe", "pods")
if output != "" {
_, _ = fmt.Fprintln(ginkgo.GinkgoWriter, output)
}
// Get the logs of apisix
output = s.GetDeploymentLogs("apisix-deployment-e2e-test")
if output != "" {
_, _ = fmt.Fprintln(ginkgo.GinkgoWriter, output)
}
// Get the logs of ingress
output = …
```

e2e: delete duplicate log data on e2e-test failure

---

.asf.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/e2e-test-ci.yml
.github/workflows/golangci-lint.yml
.github/workflows/license-checker.yml
.github/workflows/lint-checker.yml
.github/workflows/spell-checker.yml
.github/workflows/unit-test-ci.yml
.github/workflows/verify-codegen.yml

we should protect v1.5.0 branch and enable CI for it.

chore: protect v1.5.0 and enable CI for it

---

pkg/providers/ingress/translation/annotations.go
pkg/providers/ingress/translation/annotations/pluginconfig/pluginconfig.go
pkg/providers/ingress/translation/annotations/plugins/authorization.go
pkg/providers/ingress/translation/annotations/plugins/cors.go
pkg/providers/ingress/translation/annotations/plugins/cors_test.go
pkg/providers/ingress/translation/annotations/plugins/csrf.go
pkg/providers/ingress/translation/annotations/plugins/forward_auth.go
pkg/providers/ingress/translation/annotations/plugins/forward_auth_test.go
pkg/providers/ingress/translation/annotations/plugins/iprestriction.go
pkg/providers/ingress/translation/annotations/plugins/iprestriction_test.go
pkg/providers/ingress/translation/annotations/plugins/plugins.go
pkg/providers/ingress/translation/annotations/plugins/redirect.go
pkg/providers/ingress/translation/annotations/plugins/rewrite.go
pkg/providers/ingress/translation/annotations/regex/regex.go
pkg/providers/ingress/translation/annotations/types.go
pkg/providers/ingress/translation/annotations/websocket/websocket.go
pkg/providers/ingress/translation/annotations_test.go
pkg/providers/ingress/translation/translator.go

* Decouple the transformation of resources and annotations. 
* Improved code scalability.

refactor: annotations

---

pkg/providers/apisix/apisix_consumer.go

fix: type assertion failed

---

pkg/providers/ingress/ingress.go

fix: ingress class not effect in resource sync logic

---

pkg/providers/gateway/gateway_httproute.go
test/e2e/scaffold/k8s.go
test/e2e/suite-gateway/gateway_httproute.go
test/e2e/suite-plugins/suite-plugins-other/mqtt-proxy.go

feat: support update and delete for HTTPRoute

---

pkg/ingress/ingress.go

Co-authored-by: Sarasa Kisaragi <lingsamuelgrace@gmail.com>
Co-authored-by: Xin Rong <1324266492@qq.com>
* #1311

fix: ingress class not effect in resource sync logic (#1311)

---

pkg/providers/utils/status.go

fix: crd resource status is not updated

---

pkg/providers/apisix/apisix_upstream.go

fix: Using different protocols at the same time in ApisixUpstream

---

docs/en/latest/contribute.md
docs/en/latest/getting-started.md

docs: update golang version to 1.19

---

docs/en/latest/concepts/apisix_route.md

Updates the documentation of ApisixRoute concept.
Once this PR is approved, I will apply similar changes to rest of the concept docs.

docs: update ApisixRoute docs

---

docs/en/latest/getting-started.md

Update example to make sure that there is parity with both native Ingress resource and APISIX CRD.

docs: ensure parity in examples

---

docs/en/latest/getting-started.md

Fix a typo in getting start doc

docs: fix typo

---

pkg/providers/ingress/translation/translator.go
test/e2e/suite-ingress/suite-ingress-resource/ingress.go

feat: ingress extensions/v1beta1 support tls

---

pkg/api/server.go

fix: cluster.metricsCollector invoked before assign when MountWebhooks

---

pkg/providers/apisix/translation/apisix_route.go

fix: #1412

---

.github/workflows/lint-checker.yml
docs/en/latest/FAQ.md
docs/en/latest/references/apisix_upstream.md

docs: update "FAQ" page

---

docs/en/latest/contribute.md

Updates the "Development" guide and makes it consistent with APISIX guide.

docs: update "Development" guide

---

docs/en/latest/references/apisix_cluster_config_v2.md
docs/en/latest/references/apisix_cluster_config_v2beta3.md
docs/en/latest/references/apisix_pluginconfig_v2.md
docs/en/latest/references/apisix_pluginconfig_v2beta3.md
docs/en/latest/references/apisix_tls_v2.md
docs/en/latest/references/apisix_tls_v2beta3.md

docs: update API references

---

Makefile
utils/kind-with-registry.sh

https://github.com/apache/apisix-ingress-controller/issues/1416

Feat (dev env): allow to custom registry port for `make kind-up`

---

docs/en/latest/tutorials/how-to-access-Apache-APISIX-Prometheus-Metrics-on-k8s.md

According to the feedback of the community users, user can not be used prometheus correctly according to the document guidance.

docs: Add more descriptions and examples in the prometheus doc

---

pkg/kube/apisix/const/const.go
pkg/providers/apisix/translation/apisix_route.go
samples/deploy/crd/v1/ApisixRoute.yaml
test/e2e/scaffold/scaffold.go
test/e2e/suite-features/route_match_exprs.go

feat: support variable in ApisixRoute exprs scope

---

pkg/api/server.go

fix: cluster.metricsCollector invoked before assign when MountWebhooks(#1428)

---

docs/en/latest/concepts/annotations.md

Update the documentation with instructions to use "spec.ingressClassName: apisix" instead of the obsolete "metadata.annotations: kubernetes.io/ingress.class: apisix".
Mdlink checked

docs: ingress class annotation to spec (#1421)

---

pkg/apisix/consumer.go
pkg/apisix/global_rule.go
pkg/apisix/plugin.go
pkg/apisix/plugin_metadata.go
pkg/apisix/pluginconfig.go
pkg/apisix/route.go
pkg/apisix/schema.go
pkg/apisix/ssl.go
pkg/apisix/stream_route.go
pkg/apisix/upstream.go
pkg/apisix/upstreamservicerelation.go

the value is not always "default"

fix: use field cluster.name as value but not "default"

---

pkg/api/router/router_test.go

use httptest.NewRequest instead of http.Request as incoming server request.

chore: use httptest.NewRequest instead of http.Request as incoming server request in test case

---

pkg/providers/apisix/provider.go
pkg/providers/apisix/provider_init.go

Resolve: https://github.com/apache/apisix-ingress-controller/issues/1378

fix: many namespace lead to provider stuck

---

.github/workflows/e2e-test-ci-v2-cron.yml
.github/workflows/e2e-test-ci.yml
.github/workflows/k8s-timer-ci.yml

GitHub Actions is modifying its default system version, which may cause CI to fail since cgroup v2 will be used in the latest system, but not all Kubernetes versions support it.
Setting to ubuntu-20.04 will use cgroup v1, which is more general.
ref: https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

ci: using ubuntu-20.04 by default

---

pkg/providers/apisix/apisix_cluster_config.go
pkg/providers/apisix/apisix_consumer.go
pkg/providers/apisix/apisix_plugin_config.go
pkg/providers/apisix/apisix_route.go
pkg/providers/apisix/apisix_tls.go
pkg/providers/apisix/apisix_upstream.go
pkg/providers/apisix/provider.go
pkg/providers/apisix/provider_init.go
pkg/providers/controller.go
pkg/providers/ingress/ingress.go
pkg/providers/ingress/provider.go
pkg/providers/k8s/configmap/configmap.go
pkg/providers/k8s/configmap/provider.go
pkg/providers/k8s/namespace/namespace_provider.go
pkg/providers/k8s/pod/provider.go
pkg/providers/types/types.go

fix:
With the increase of functional requirements, the interdependence between resources is inevitable. We should unify the informer structure to avoid errors caused by resources not being ready.

refactor: unified factory and informer

---

docs/en/latest/tutorials/proxy-the-httpbin-service.md

Updates the tutorial about using APISIX CRDs to configure Ingress.

docs: update APISIX CRD tutorial

---

docs/en/latest/tutorials/the-hard-way.md

fix a docs error where create configmap before create apisix deployment.

docs: Update the-hard-way.md

---

pkg/providers/apisix/translation/apisix_route.go
pkg/providers/apisix/translation/apisix_route_test.go
test/e2e/suite-plugins/suite-plugins-other/plugin_config.go

This PR fixes the issue of ignoring passed PluginConfigName in case ApisixRoute definition contains only upstreams and not backends configuration.
The issue is described here in detail - https://github.com/apache/apisix-ingress-controller/issues/1577.

fix: allow passing plugin config name for route with no backends

---

pkg/providers/apisix/translation/apisix_route.go
pkg/providers/apisix/translation/apisix_route_test.go
test/e2e/suite-plugins/suite-plugins-other/plugin_config.go

[v1.6 cherry-pick]fix: allow passing plugin config name for route with no backends (#1578)

---

.github/workflows/goimports-reviser.yml
pkg/providers/ingress/translation/annotations/plugins/http_method.go
pkg/providers/ingress/translation/annotations/plugins/http_method_test.go
test/e2e/suite-chore/admin_api.go
test/e2e/suite-features/external-sd.go
test/e2e/suite-plugins/suite-plugins-general/secret_ref.go

Signed-off-by: Gallardot <tttick@163.com>

ci: add goimports-reviser

---

docs/en/latest/concepts/apisix_global_rule.md

Maybe someone forgot to add the `-` letter :)

docs: fix type of .spec.plugins

---

docs/en/latest/tutorials/how-to-access-Apache-APISIX-Prometheus-Metrics-on-k8s.md

Updates the tutorial on using Prometheus with Apache APISIX Ingress.

docs: update Prometheus tutorial

---

pkg/providers/ingress/ingress.go
pkg/providers/ingress/translation/translator.go
test/e2e/suite-ingress/suite-ingress-resource/ingress.go

fix: fix sync delete svc error

---

pkg/providers/ingress/translation/translator.go
test/e2e/suite-ingress/suite-ingress-resource/ingress.go

Signed-off-by: Basuotian <basuoluomiu@gmail.com>
Fix: #1659

fix: panic at empty http spec

---

docs/en/latest/tutorials/the-hard-way.md

1. where is no apisix 2.15-alpine image in docker hub, with 2.15 and base image on alpine, there is 2.15.0-alpine in the hub, so if someone follow the doc will get imagePullErr.
2. I just test apisix-ingress-controller the original version 1.4.0 works, but the newest version is to 1.6.0, so maybe update the ingress controller image version is also needed.

docs: update the apisix image version and ingress image version

---

cmd/ingress/ingress.go
pkg/providers/controller.go

The function can be useless if the user has never messed up ingress controller managed resources in APISIX. It should be able to be disabled.
Also, the default value `5m` is too small.  Every sync writes to etcd, causing etcd to store too many history records, making the dbsize grow dramatically over time.
(also fixes a small problem, `defer` shouldn't in loop)

feat: support disable resource periodically sync

---

pkg/api/server.go
pkg/log/gin_logger.go
pkg/log/gin_logger_test.go

close: #1546
`gin_logger` now does not require passing of `DefaultLogger` to it. It uses the same logger as other parts.

fix: set the health check log level by gin to debug

---

.github/workflows/e2e-test-ci.yml
test/e2e/scaffold/scaffold.go

ci: regression test on apisix-and-all and apisix

---

cmd/ingress/ingress.go
cmd/ingress/ingress_test.go
pkg/providers/apisix/apisix_tls.go
pkg/providers/controller.go
pkg/providers/k8s/endpoint/endpoint.go
pkg/providers/k8s/endpoint/endpointslice.go
pkg/providers/k8s/secret.go
samples/deploy/rbac/apisix_view_clusterrole.yaml
test/e2e/suite-ingress/suite-ingress-features/secret.go

Fixes #1190
Cache `ApisixTls -> Secret` relationship even if the translation failed. This can fix secret created later than ApisixTls case.

bugfix: fix secret created later than apisixtls

---

pkg/providers/gateway/translation/gateway_httproute.go
pkg/providers/gateway/translation/gateway_httproute_test.go
pkg/providers/gateway/translation/gateway_tlsroute.go
pkg/providers/gateway/translation/gateway_udproute.go
pkg/providers/k8s/secret.go

Bugfix: should set `upstream.Name` since `TranslateContext` use it as the key. Otherwise, the generated upstream will be ignored.

fix: missing upstream name in gateway-api routes

---

cmd/ingress/ingress.go
cmd/ingress/ingress_test.go
pkg/providers/apisix/apisix_tls.go
pkg/providers/controller.go
pkg/providers/k8s/endpoint/endpoint.go
pkg/providers/k8s/endpoint/endpointslice.go
pkg/providers/k8s/secret.go
samples/deploy/rbac/apisix_view_clusterrole.yaml
test/e2e/suite-ingress/suite-ingress-features/secret.go

[cherry-pick] fix: when secret created later than apisixtls it should be updated (#1715)

---

pkg/providers/gateway/translation/gateway_httproute.go
pkg/providers/gateway/translation/gateway_httproute_test.go
pkg/providers/gateway/translation/gateway_tlsroute.go
pkg/providers/gateway/translation/gateway_udproute.go
pkg/providers/k8s/secret.go

[cherry-pick] fix: missing upstream name in gateway-api routes (#1754)

---

docs/en/latest/deployments/kind.md

Installing ingress controller with Kind on a clean Debian today. Installed the three pre-req items but still got the following: 
```
$ kind create cluster
ERROR: failed to create cluster: failed to get docker info: command "docker info --format '{{json .}}'" failed with error: exec: "docker": executable file not found in $PATH
```
Looks like Docker should be added

docs: added Docker to prerequisite of Installation with Kind 

---

docs/en/latest/concepts/apisix_plugin_config.md
docs/en/latest/concepts/apisix_route.md
docs/en/latest/config.json

Fixes #1552
Updates concepts/ApisixRoute docs with a better example of using a Plugin and adds documentation for the ApisixPluginConfig CRD.

docs: add ApisixPluginConfig and update examples

---

docs/en/latest/tutorials/mtls.md

This PR addresses issue #1767, which highlights a lack of documentation on how to generate a Kubernetes secret from a cert file. Specifically, the current documentation for protecting a route using SSL with the Apache APISIX Ingress Controller does not provide information on the format and meaning of the secret or how to generate it.
To address this issue, this PR adds detailed instructions on generating a Kubernetes secret from a cert file. The updated documentation includes the meaning and format of the secret, as well as commands to generate the base64 value of the cert and private key files. With these instructions, users will be able to properly generate a secret and use it to protect their routes using SSL with the Apache APISIX Ingress Controller.
Overall, this PR improves the …

docs: describe how to generate secret from cert file

---

Dockerfile
Makefile

Cache go build cache to speedup builds in development env.

chore: use docker buildkit to cache go build cache

---

.github/workflows/e2e-test-ci-v2-cron.yml
.github/workflows/e2e-test-ci.yml
.github/workflows/k8s-timer-ci.yml
Makefile

upgrade CI  ginkgo 1.9.0 to 1.9.2，reference (#1799)

Chore:   upgrade CI  ginkgo 1.9.0 to 1.9.2

---

pkg/apisix/cluster.go
pkg/providers/controller.go

Keep health checker running when health check failed. 
Make health check function pure.
Bugfix
for #1760

fix: health check bug

---

test/e2e/testdata/ldap/cmd.sh
test/e2e/testdata/wolf-rbac/cmd.sh

This PR makes `docker-compose` and `docker compose` compatible. The source issue(#1201) is this. 
This PR will solve the problem of `docker-compose` not being found when doing the e2e-test locally.

chore: Make docker compose and docker-compose compatible

---

pkg/providers/gateway/gateway_httproute.go
pkg/providers/gateway/gateway_tcproute.go

fix: Referencing empty objects during tcproute and httproute updates

---

docs/en/latest/tutorials/cert-manager/issuer.yaml

error: resource mapping not found for name: "ca-issuer" namespace: "" from "issuer.yaml": no matches for kind "Issuer" in version "cert-manager.io/v1alpha2"
ensure CRDs are installed first
https://cert-manager.io/docs/installation/upgrading/remove-deprecated-apis/

docs: Update issuer.yaml

---

docs/en/latest/concepts/annotations.md
pkg/providers/ingress/translation/annotations/plugins/response_rewrite.go
pkg/providers/ingress/translation/annotations/plugins/response_rewrite_test.go
pkg/providers/ingress/translation/annotations/types.go
pkg/types/apisix/v1/plugin_types.go

Allows users to use the header manipulation feature of response-rewrite plugin in APISIX via annotations in Ingress resource. Solves #1860 
Example
Case 1:  Remove `Server` header
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: httpserver-ingress
annotations:
k8s.apisix.apache.org/response-rewrite-remove-header: "Server"
k8s.apisix.apache.org/enable-response-rewrite: "true"
spec:
ingressClassName: apisix
rules:
- host: mockbin.org
http:
paths:
- backend:
service:
name: httpbin
port:
number: 80
path: / 
pathType: Prefix
````
No server header in response
---
Case 2: Adding headers
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: httpserver-ingress
annotations:
k8s.apisix.apache.org/response-rewrite-add-header: "testkey1:testval1,testkey2:testval2" …
```

feat: Allow response header rewrite via Ingress annotations

---

docs/en/latest/FAQ.md

Solves #1895 
This PR adds answer to a commonly asked question by users.

docs: Add QA about exposing gateway as loadbalancer

---

pkg/providers/controller.go

```
2023-08-31T02:45:31Z	info	ingress/ingress.go:145	start ingress controller
2023-08-31T02:45:31Z	error	providers/controller.go:236	failed to create leader elector: Lock identity is empty
2023-08-31T02:45:31Z	error	providers/controller.go:156	failed to setup leader election
failed to run ingress controller: Lock identity is empty
FAIL	github.com/apache/apisix-ingress-controller/cmd/ingress	0.056s
```
https://github.com/apache/apisix-ingress-controller/actions/runs/6032435340/job/16367603625?pr=1936#step:4:154

feat: use HOSTNAME as controller name and add default value.

---

Makefile

Split run-e2e-test to separate action, so that we can just run e2e test without running other dependencies actions, it will make our testing in the local environment more flexible.

chore: split run-e2e-test to separate action

---

pkg/providers/apisix/apisix_consumer.go
pkg/providers/apisix/apisix_global_rule.go
pkg/providers/apisix/apisix_plugin_config.go
pkg/providers/apisix/apisix_route.go
pkg/providers/apisix/apisix_tls.go
pkg/providers/apisix/apisix_upstream.go
pkg/providers/apisix/provider.go
pkg/providers/controller.go
pkg/providers/ingress/ingress.go
pkg/providers/ingress/provider.go
pkg/providers/k8s/namespace/namespace.go
pkg/providers/k8s/namespace/namespace_provider.go
test/e2e/suite-ingress/suite-ingress-features/namespace.go

- [x ] Bugfix
I deploy apisix with namespace_selector option. If I apply apisixroute in a namespace, and then label with that namespace. It does not work.
Example:
1. deploy apisix with namespace_selector option
```
kubernetes:
namespace_selector:
- apisix=true
```
2. deploy apisixroute
```
kubectl create ns test
kubectl apply -f  -  <<EOF
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
name: nginx
namespace: test
spec:
http:
- backends:
- serviceName: nginx
servicePort: 80
match:
hosts:
- xx.com
paths:
- /*
name: nginx
EOF
kubectl label ns test apisix=true
```
apisix-ingress-controller does not sync that apisixroute after I label that namespace.

fix: sync resource after namespace changed

---

pkg/apisix/plugin_metadata.go

Fix `plugin_metadata_cm` not working due to populating to wrong etcd key
Before this fix, this can be seen in the debug log
```
2023-10-18T11:31:03+08:00	[35mdebug[0m	apisix/cluster.go:1225	push event to adapter	{"event": "create", "key": "/apisix/plugin_metadatas/datadog", "value": "{\"host\":\"datadog.datadog\",\"namespace\":\"apisix\",\"port\":8125}"}
```

fix: plugin_metadata not populating to the correct etcd key

---

pkg/apisix/plugin_metadata.go

Bugfix #2012 port to 1.7
(cherry picked from commit 4d004e1a5a824bc48383e37ef7755b9aafb6aaac)

[cherry-pick] fix: plugin_metadata not populating to the correct etcd key (#2012)

---

docs/en/latest/concepts/apisix_global_rule.md

Renamed `enabled` to `enable` according to CRD
Fixed a mistake in docs.

Renamed field in examples according to CRD

---

Makefile

chore: correct Makefile comments

---

docs/en/latest/tutorials/how-to-avoid-race-condition-when-scaling-down.md

docs: add best practice docs to avoid race condition bw kubelet and apisix

---

pkg/providers/apisix/apisix_cluster_config.go
pkg/providers/apisix/apisix_consumer.go
pkg/providers/apisix/apisix_global_rule.go
pkg/providers/apisix/apisix_plugin_config.go
pkg/providers/apisix/apisix_route.go
pkg/providers/apisix/apisix_tls.go
pkg/providers/apisix/apisix_upstream.go
pkg/providers/ingress/ingress.go

fixes #2060 
The string comparison in go is lexicographically per unicode point therefore "9" > "10". 
So instead the variables should be type converted into int before comparison

fix: replace string comparison with 64 bit int

---

docs/en/latest/deployments/ack.md
docs/en/latest/deployments/aws.md
docs/en/latest/deployments/azure.md
docs/en/latest/deployments/gke.md
docs/en/latest/deployments/k3s-rke.md
docs/en/latest/deployments/kind.md
docs/en/latest/deployments/kubesphere.md
docs/en/latest/deployments/minikube.md
docs/en/latest/deployments/openshift.md
docs/en/latest/deployments/tke.md
docs/en/latest/tutorials/configure-ingress-with-gateway-api.md
docs/en/latest/tutorials/how-to-use-go-plugin-runner-in-apisix-ingress.md
docs/en/latest/tutorials/istio-egress-gateway.md
docs/en/latest/tutorials/manage-certificates-with-cert-manager.md
docs/en/latest/tutorials/manage-ingress-certificates-with-cert-manager.md
docs/en/latest/tutorials/mtls.md
docs/en/latest/tutorials/proxy-grpc-service.md
docs/en/latest/tutorials/using-custom-plugins.md
docs/en/latest/upgrade.md

Currently the key value pair references the helm chart from master. But by default, the helm chart from dev branch is downloaded. So the key value pairs are updated accordingly.

docs: update keys based helm chart version

---

samples/deploy/crd/v1/ApisixRoute.yaml

Fixes https://github.com/apache/apisix-ingress-controller/issues/1927
APISIX does not have this URI validation and allows for paths like `/abc/*/abc` whereas the schema validation in K8s CR makes rules where `*` cannot be added in the middle. This PR removes the `pattern` field to remove route string validation at this level and let APISIX handle it.

fix: remove path validation

---

cmd/ingress/ingress.go
pkg/providers/controller.go

(verbatin commit message)
this commit changes the signal handling in cmd/ingress to be wrapped in a context, and inverts which goroutine runs the controller and which watches for the context to be cancelled, which allows some scaffolding (`sync.WaitGroup`) to be removed and now properly handles the controller exiting with `nil` (as it does when leader election fails)

refactor(cmd/ingress): invert signal ctx logic

---

pkg/types/labels_test.go
samples/deploy/crd/v1/ApisixRoute.yaml

the test relied on wrong type of array assertions which assumed consistent order preservation. this commit uses assert.Subset instead
Example of failure https://github.com/apache/apisix-ingress-controller/actions/runs/7725975728/job/21061338039?pr=2148

test: failing flaky unit test

---

pkg/apisix/cluster.go

Because apisix uses local cache for reference checking, deleting may fail due to slow cache synchronization. Apisix has already provided a parameter（force） in the deletion of API to address this issue. Ingress controllers should use this parameter to delete resources and avoid resource leakage.

fix: use force=true to hard delete the apisix resource

---

pkg/apisix/cluster.go
pkg/providers/apisix/apisix_upstream.go

chore: remove redundant logs and improve logs for users

---

pkg/apisix/cache/cache.go
pkg/apisix/cache/memdb.go
pkg/apisix/cache/noop_db.go
pkg/apisix/nonexistentclient.go
pkg/apisix/pluginconfig.go
pkg/apisix/upstream.go

After adding the force=true flag in requests to apisix, we cant rely on apisix reference counting to not delete resources and will have to check it at ingress level before sending request to apisix.
1. Create a route1 referencing a service
2. Check that an upstream is created in APISIX.
3. Create another route, route2 referencing the same service.
4. Delete route1.
5. Check APISIX to see that the upstream is not deleted.
6. Delete route2
7. Upstream is deleted.

fix: deletion of references

---

pkg/providers/apisix/apisix_global_rule.go

Users encountered the error:
```bash
2024-10-02T19:24:30+08:00 [31merror[0m adapter/etcd.go:141 failed to create object, ignore it{error 26 0 rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 625 <nil>} {key 15 0 /apisix/global_rules/c6bbeaf1 <nil>}
```
This error only comes for global rule and only comes in candidate controllers.
Reason:
In current logic, the candidate controllers miss the .Forget() call on the successfully processed object and re-add the object in the workqueue. This fix makes sure that event is removed from the queue when object is processed successfully.
How to reproduce the bug:
1. Run make kind-up
2. Modify replica to 3 and apply samples/deploy/composite.yaml
3. Create an ApisixGlobalRule.
4. Check logs of follower …

fix: candidate controllers missing Forget call in workqueue

---

pkg/providers/controller.go

Fixes #1980.
Simpler version of #2152 that shouldn't break any tests, since it doesn't touch leader election.
Also addresses #2236.
This one just adds communicating failure from `run` back to `Run`, tried to shut down gracefully, but forces a shutdown after 5 seconds.
Still wouldn't recommend running two replicas, the code has some potential races.

fix: attempt to shut down when provider init fails

---

.github/workflows/e2e-test-ci-v2-cron-dev.yml
.github/workflows/e2e-test-ci-v2-cron.yml
.github/workflows/e2e-test-ci.yml
.github/workflows/k8s-timer-ci.yml

Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible.

chore: upgrade actions/upload-artifact and actions/download-artifact

---

.github/workflows/e2e-test-ci-v2-cron-dev.yml
.github/workflows/e2e-test-ci-v2-cron.yml
.github/workflows/e2e-test-ci.yml
.github/workflows/k8s-timer-ci.yml

Description
In light of the deprecation of 20.04 - https://github.com/actions/runner-images/issues/11101

chore: upgrade ubuntu from 20.04 to latest

---

api/v2/apisixconsumer_types.go
api/v2/apisixglobalrule_types.go
api/v2/apisixpluginconfig_types.go
api/v2/apisixroute_types.go
api/v2/apisixtls_types.go
api/v2/apisixupstream_types.go
config/crd/bases/apisix.apache.org_apisixconsumers.yaml
config/crd/bases/apisix.apache.org_apisixglobalrules.yaml
config/crd/bases/apisix.apache.org_apisixpluginconfigs.yaml
config/crd/bases/apisix.apache.org_apisixroutes.yaml
config/crd/bases/apisix.apache.org_apisixtlses.yaml
config/crd/bases/apisix.apache.org_apisixupstreams.yaml

fix(crd): missing shortname and printcolumn

---

.github/workflows/apisix-conformance-test.yml
Makefile
config/samples/config.yaml
internal/controller/config/config.go

failed to run:
```shell
$ ./bin/apisix-ingress-controller_amd64
Error: sync_period must be greater than 0 for standalone provider
Usage:
apisix-ingress-controller [command] [flags]
apisix-ingress-controller [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
version     version for apisix-ingress-controller
```

fix: the sync_period of the provider should not be 0s

---

internal/provider/adc/adc.go

```txt
2025-07-04T06:25:04Z        [31merror[0m        adc/adc.go:344        no adc configs provided        {"task": {"Name":"apisix","Resources":{},"Labels":null,"ResourceTypes":null}}
2025-07-04T06:25:04.168Z        ERROR        controller-runtime        controller/controller.go:316        Reconciler error        {"controller": "gateway", "controllerGroup": "gateway.networking.k8s.io", "controllerKind": "Gateway", "Gateway": {"name":"apisix","namespace":"api7-ee-e2e"}, "namespace": "api7-ee-e2e", "name": "apisix", "reconcileID": "e924b63b-25b9-46bb-925c-3131cd8726b6", "error": "no adc configs provided", "errorVerbose": "no adc configs provided\ngithub.com/apache/apisix-ingress-controller/internal/provider/adc.(*adcClient).sync\n\t/home/runner/work/apisix-ingress-controller/apisix-ingress …
```

fix: config not provided should not be retried

---

internal/provider/adc/cache/indexer.go
test/e2e/apisix/route.go

For the following set of resources, it will only take effect for the last resource.
```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
name: route-11111
spec:
ingressClassName: apisix
http:
- name: rule0
match:
hosts:
- httpbin-11111
paths:
- /*
backends:
- serviceName: httpbin
servicePort: 80
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
name: route-1111
spec:
ingressClassName: apisix
http:
- name: rule0
match:
hosts:
- httpbin-1111
paths:
- /*
backends:
- serviceName: httpbin
servicePort: 80
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
name: route-111
spec:
ingressClassName: apisix
http:
- name: rule0
match:
hosts:
- httpbin-111
paths:
- /*
backends:
- serviceName: httpbin
servicePort: 80
---
apiVersion: apisix.apache.org/v2
kind: …
```

fix: route names with the same prefix were mistakenly deleted

---

internal/controller/apisixconsumer_controller.go
internal/controller/apisixglobalrule_controller.go
internal/controller/apisixroute_controller.go
internal/controller/apisixtls_controller.go
internal/controller/consumer_controller.go
internal/controller/httproute_controller.go
internal/controller/indexer/indexer.go
internal/controller/ingress_controller.go
internal/controller/status/updater.go
internal/controller/utils.go
internal/manager/controllers.go
internal/manager/readiness/manager.go
internal/manager/run.go
internal/provider/adc/adc.go
internal/provider/provider.go
internal/types/k8s.go
test/e2e/apisix/route.go
test/e2e/crds/consumer.go
test/e2e/gatewayapi/httproute.go

The controller watches CRDs and incrementally builds an in-memory cache of dataplane resources. It periodically performs a full (asynchronous) sync from this cache to the dataplane, without waiting for the cache to be fully populated.
On startup, if the number of CRDs is large, the first full sync may happen before all resources are processed, resulting in partial configuration being pushed to the dataplane. This can cause temporary 404 errors and traffic disruption.
1. Apply 5,000 ApisixRoute to the kubernetes cluster.
2. Restart the Ingress controller.
3. While the Ingress controller is starting, attempt to access all routes via the data plane. Some routes will return 404 Not Found errors.

fix: full sync during restart results in loss of dataplane traffic

---

internal/provider/adc/translator/apisixroute.go
test/e2e/crds/v2/route.go
test/e2e/scaffold/apisix_deployer.go
test/e2e/scaffold/deployer.go

This PR solves two bugs and adds corresponding E2E tests:
1. `backendErr` is currently a shared variable due to which even if one backend is invalid, no backend is set causing 0 nodes to be set on upstream even when there are valid nodes. A test case confirming the fix for this has been added. The test `valid backend is set even if other backend is invalid` confirms this fix.
2. The weight from backend was not set in the upstream  label which is used to set weight on `weightedUpstreams` due to which all nodes always get `100` as weight. The tests `2:1 traffic split test` and `zero-weight test` confirm this fix.

fix: traffic-split weight distribution and add e2e tests

---

docs/en/latest/reference/example.md

Fix indentation in reference doc. The configuration previously will lead to `error: error parsing test.yaml: error converting YAML to JSON: yaml: line xx: did not find expected '-' indicator`
https://github.com/apache/apisix-ingress-controller/issues/2510
Will open a PR for master as well.

docs: fix indentation in reference doc

---

api/adc/types.go
test/e2e/gatewayapi/httproute.go
test/e2e/scaffold/assertion.go

In the type definition, they are mandatory. If only add is set, the other two will be empty arrays and empty objects, respectively:
https://github.com/apache/apisix-ingress-controller/blob/ec8624b11d5c71d6904c6f9b292b260794db3e5f/api/adc/types.go#L637-L641
When only one of add, set, or remove is defined, schema validation (e.g., minItems=1) cannot be guaranteed by the data plane.
https://github.com/apache/apisix/blob/9e34661e7edb57fa76a215333b92c6d086e80076/apisix/plugins/response-rewrite.lua#L59-L80

fix: responseHeaderModifier fails to synchronize

---

docs/en/latest/concepts/gateway-api.md
docs/en/latest/configure.md
docs/en/latest/getting-started/configure-routes.md
docs/en/latest/getting-started/key-authentication.md
docs/en/latest/getting-started/load-balancing.md
docs/en/latest/getting-started/rate-limiting.md
docs/en/latest/reference/example.md
docs/en/latest/upgrade-guide.md

Currently the doc explicitly sets the preferred namespace with `kubectl config set-context --current --namespace=ingress-apisix` and leaves out the namespace specification in manifest file. However if users did not read the docs sequentially and set the preferred namespace, resources could be applied to the wrong namespace, leading to downstream issues.
This PR explicitly sets namespace in metadata.

docs: specify namespace in metadata explicitly

---

docs/en/latest/getting-started/key-authentication.md
docs/en/latest/getting-started/load-balancing.md
docs/en/latest/getting-started/rate-limiting.md
docs/en/latest/reference/example.md

Should specify ingressClassName when there are multiple ingress controllers and ingress classes in the cluster.

docs: add ingressClassName to explicitly specify which ingress class should handle each resource
